// react-app/src/components/profile/Profile.tsx
import { useContext, useState } from 'react'
import { AuthContext } from '../../contexts/authContext'
import { IconButton, Icon } from '@mui/material';
import styles from './Profile.module.css';

export const Profile = () => {
  const [ open, setOpen ] = useState(false);
  const { user, logout } = useContext(AuthContext);

  const toggle = () => {
    setOpen(pre => !pre);
  }

  const exit = () => {
    logout();
  }

  return (
    <div id={styles["profile"]}> {/* (clickOutside)="close()" */}
      <IconButton id={styles["profile-button"]} onClick={toggle}>
        <Icon className={styles["profile-icon"]}>manage_accounts</Icon>
      </IconButton>
      <section className={`${styles["profile-data"]} ${open ? styles["open"] : ''}`}>
        <div id={styles["profile-username"]}>
          <div>{user!.username}</div>
          <div id={styles["profile-role"]}>{user!.role.name}</div>
        </div>
        <div className={styles["profile-details"]}>
          <div>{user!.name}</div>
          <div>{user!.email}</div>
          <div id={styles["profile-footer"]}>
            <span>Regisztráció: {user!.created.split('T')[0]}</span>
            <IconButton title="Kilépés" color="error" onClick={exit}>
              <Icon>logout</Icon>
            </IconButton>
          </div>
        </div>
      </section>
    </div>
  )
}

// angular/src/app/components/profile/profile.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { User } from 'src/app/models/user.model';
import { AuthService } from 'src/app/services/auth.service';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css']
})
export class ProfileComponent implements OnInit {
  open: boolean;
  @Input() user?: User;
  constructor(private authService: AuthService) {
    this.open = false;
  }

  ngOnInit(): void {
  }

  toggle = () => {
    this.open = !this.open;
  }

  close = () => {
    this.open = false;
  }

  exit = () => {
    this.authService.logout();
  }
}

<div id="profile" (clickOutside)="close()">
  <button mat-icon-button id="profile-button" (click)="toggle()">
    <mat-icon class="profile-icon">manage_accounts</mat-icon>
  </button>
  <section class="profile-data" *ngIf="open">
    <div id="profile-username">
      <div>{{user!.username}}</div>
      <div id="profile-role">{{user!.role.name}}</div>
    </div>
    <div class="profile-details">
      <div>{{user!.name}}</div>
      <div>{{user!.email}}</div>
      <div id="profile-footer">
        <span>Regisztráció: {{user!.created.split('T')[0]}}</span>
        <button mat-icon-button title="Kilépés" color="warn" (click)="exit()">
          <mat-icon>logout</mat-icon>
        </button>
      </div>
    </div>
  </section>
</div>
