// react-app/src/components/backend-chooser/BackendChooser.tsx
import styles from './BackendChooser.module.css';
import { Icon, IconButton, RadioGroup, Radio, FormControlLabel } from '@mui/material';
import { useContext, useEffect, useState } from 'react';
import { AuthContext } from '../../contexts/authContext';

export const BackendChooser = () => {
  const [ open, setOpen] = useState(false);
  const [ activeName, setActiveName ] = useState("");
  const { getActiveBackendName, setBackendLocation } = useContext(AuthContext);

  useEffect(() => {
    setActiveName(getActiveBackendName());
  }, [getActiveBackendName]);

  const toggle = () => {
    setOpen(pre => !pre);
  }

  const setActiveBackend = (event: any) => {
    setActiveName(event.target.value);
    setBackendLocation(event.target.value);
  }

  return (
    <div id={styles["backend-chooser"]}> {/* (clickOutside)="close()" */}
      <IconButton id={styles["backend-chooser-button"]} onClick={toggle}>
        <Icon className={styles["backend-chooser-icon"]}>settings</Icon>
      </IconButton>
      <section className={`${styles["backend-chooser-data"]} ${open ? styles["open"] : ""}`}>
          <div>
            <h3>Backend választás!</h3>
          </div>
          <RadioGroup aria-label="Válassz backend-et!" value={activeName} onChange={setActiveBackend}>
            <div className={styles["radio-button-container"]}>
              <FormControlLabel value="fastify" control={<Radio size='medium' />} label="Fastify" />
            </div>
            <div className={styles["radio-button-container"]}>
              <FormControlLabel value="express" control={<Radio size='medium' />} label="Express" />
            </div>
            <div className={styles["radio-button-container"]}>
              <FormControlLabel disabled value="spring" control={<Radio size='medium' />} label="Spring" />
            </div>
          </RadioGroup>
      </section>
    </div>
  )
}

// angular/src/app/components/backend-chooser/backend-chooser.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from 'src/app/services/auth.service';

@Component({
  selector: 'app-backend-chooser',
  templateUrl: './backend-chooser.component.html',
  styleUrls: ['./backend-chooser.component.css']
})
export class BackendChooserComponent implements OnInit {
  open: boolean;
  constructor(private authService: AuthService) {
    this.open = false;
  }

  ngOnInit(): void {
  }

  toggle = () => {
    this.open = !this.open;
  }

  close = () => {
    this.open = false;
  }

  isChecked = (name: string) => {
    return this.authService.isBackendActive(name);
  }

  changeBackend = (name: string) => {
    this.authService.changeBackendLocation(name);
  }
}

<div id="backend-chooser" (clickOutside)="close()">
  <button mat-icon-button id="backend-chooser-button" (click)="toggle()">
    <mat-icon class="backend-chooser-icon">settings</mat-icon>
  </button>
  <section class="backend-chooser-data" [ngClass]="{'open': open}">
      <div>
        <h3>Válaszd ki a használandó backend-et!</h3>
      </div>
      <mat-radio-group aria-label="Válassz backend-et!">
        <div class="radio-button-container">
          <mat-radio-button [checked]="isChecked('express')" value="express" color="primary" (click)="changeBackend('express')">Express</mat-radio-button>
        </div>
        <div  class="radio-button-container">
          <mat-radio-button [checked]="isChecked('fastify')" value="fastify" color="primary" (click)="changeBackend('fastify')">Fastify</mat-radio-button>
        </div>
      </mat-radio-group>
  </section>
</div>
