// angular/src/app/pages/handlers/newsfeed-handler/newsfeed-handler.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';
import { MatSnackBar } from '@angular/material/snack-bar';
import { ActivatedRoute, Router } from '@angular/router';
import { ConfirmationComponent } from 'src/app/components/items/confirmation/confirmation.component';
import { DropdownItem, ErrorMessage } from 'src/app/models/menu.model';
import { Newsfeed } from 'src/app/models/newsfeed.model';
import { Series } from 'src/app/models/series.model';
import { NewsfeedService } from 'src/app/services/newsfeed.service';
import { SeriesService } from 'src/app/services/series.service';

@Component({
  selector: 'app-newsfeed-handler',
  templateUrl: './newsfeed-handler.component.html',
  styleUrls: ['./newsfeed-handler.component.css']
})
export class NewsfeedHandlerComponent implements OnInit {
  formGroup!: FormGroup;
  addNew: boolean;
  newsfeedId?: number;
  series?: Series;
  newsfeedOptions: DropdownItem[];
  seriesOptions: DropdownItem[];
  private selectedNewsfeed?: Newsfeed;
  constructor(private router: Router,
              private route: ActivatedRoute,
              private snackbar: MatSnackBar,
              private fb: FormBuilder,
              private newsfeedService: NewsfeedService,
              private seriesService: SeriesService,
              private dialog: MatDialog) {
    this.addNew = true;
    this.newsfeedOptions = [];
    this.seriesOptions = [];
  }

  async ngOnInit() {
    this.formGroup = this.fb.group({
      title: ['', [Validators.required]],
      description: ['', [Validators.required]]
    });

    const tempId = this.route.snapshot.paramMap.get("id");
    if(tempId) {
      this.addNew = false;
      this.newsfeedId = Number(tempId);

      try {
        this.selectedNewsfeed = await this.newsfeedService.getNewsfeed(this.newsfeedId);
        this.setValues(this.selectedNewsfeed);
      } catch(err) {
        this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
        this.router.navigateByUrl(`/admin/newsfeed`, { replaceUrl: true });
      }
    }
  }

  isValid = () => {
    return this.formGroup.valid && this.series !== undefined;
  }

  submit = async () => {
    if(!this.formGroup.valid || this.series === undefined) {
      return;
    }

    const formNewsfeed: Newsfeed = {
      title: this.formGroup.get("title")?.value,
      description: this.formGroup.get("description")?.value,
      series: {
        id: this.series?.id as number,
        title: this.series.title,
        prodYear: this.series.prodYear,
      }
    } as Newsfeed;
    if(this.addNew) {
      try {
        const response = await this.newsfeedService.saveNewsfeed(formNewsfeed);
        if(response) {
          this.snackbar.open("Újdonság hozzáadása sikeres!", 'X', { duration: 3000, verticalPosition: 'bottom', panelClass: ['snackbar-success'] });
        }
        this.resetValues();
      } catch(err) {
        this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
      }
    } else {
      if(!this.newsfeedId) {
        this.snackbar.open("Hiba lépett fel, töltsd újra a módosítandó újdonságot", 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
        return;
      }
      try {
        const response = await this.newsfeedService.updateNewsfeed(this.newsfeedId, formNewsfeed);
        if(response) {
          this.snackbar.open(response, 'X', { duration: 3000, verticalPosition: 'bottom', panelClass: ['snackbar-success'] });
        }
      } catch(err) {
        this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
      }
    }
  }

  remove = async () => {
    const dialogRef = this.dialog.open(ConfirmationComponent, {
      data: {
        question: "Biztos hogy szeretnéd törölni?"
    }})

    dialogRef.afterClosed().subscribe(async (response) => {
      if(response) {
        if(!this.newsfeedId) {
          this.snackbar.open("Nem sikerült törölni, töltsd újra a törlendő újdonságot!", 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
          return;
        }

        try {
          const res = await this.newsfeedService.deleteNewsfeed(this.newsfeedId);
          if(res) {
            this.snackbar.open(res, 'X', { duration: 3000, verticalPosition: 'bottom', panelClass: ['snackbar-success'] });
            this.router.navigateByUrl(`/admin/newsfeed`, { replaceUrl: true });
          }
        } catch(err) {
          this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
        }
      }
    });
  }

  autocompleteValue = async (value: any) => {
    if(!isNaN(value)) {
      this.newsfeedId = value as number;
      await this.router.navigateByUrl(`/admin/newsfeed/${this.newsfeedId}`, { replaceUrl: true });
      try {
        this.setValues(await this.newsfeedService.getNewsfeed(this.newsfeedId));
      } catch(err) {
        this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
      }
    }
  }

  captureValue = async (value: string) => {
    try {
      const response = await this.newsfeedService.getNewsfeeds(1, 10, value);
      this.newsfeedOptions = response.newsfeeds
      ? response.newsfeeds
        .map((newsfeed) => ({
          value: newsfeed.id,
          shownValue: `${newsfeed.title} | ${newsfeed.series.title}`
        }) as DropdownItem)
      : [];
    } catch(err) {
      this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
    }
  }

  autocompleteSeriesValue = async (value: any) => {
    if(!isNaN(value)) {
      try {
        this.series = await this.seriesService.getSeries(value);
      } catch(err) {
        this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
      }
    }
  }

  captureSeriesValue = async (value: string) => {
    try {
      const response = await this.seriesService.getSerieses(1, 10, value);
      this.seriesOptions = response.serieses
      ? response.serieses
        .map((series) => ({
          value: series.id,
          shownValue: `${series.title}, ${series.prodYear}`
        }) as DropdownItem)
      : [];
    } catch(err) {
      this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
    }
  }

  setValues = (newsfeed: Newsfeed) => {
    this.formGroup.setValue({
      title: newsfeed.title,
      description: newsfeed.description
    });

    this.series = newsfeed.series as Series;
  }

  resetValues = () => {
    this.formGroup.setValue({
      title: '',
      description: ''
    })

    this.series = undefined;
    this.newsfeedId = undefined;
    this.selectedNewsfeed = undefined;
  }

  routeTo = (type: string) => {
    switch (type) {
      case "new":
        this.addNew = true;
        this.resetValues();
        this.router.navigateByUrl("/admin/newsfeed", { replaceUrl: true });
        return;
      case "change":
        this.addNew = false;
        this.resetValues();
        this.router.navigateByUrl(`/admin/newsfeed`, { replaceUrl: true });
        return;
      default:
        return;
    }
  }
}

<div>
  <div class="sub-navbar">
    <a (click)="routeTo('new')" class="sub-navbar-item">Új hozzáadás</a>
    <a (click)="routeTo('change')" class="sub-navbar-item">Módosítás</a>
  </div>
  <div class="container">
    <div class="search" *ngIf="!addNew">
      <app-search-bar [options]="newsfeedOptions" (searchValue)="captureValue($event)" (selectedValue)="autocompleteValue($event)"></app-search-bar>
    </div>
    <div class="form-container" *ngIf="addNew || newsfeedId">
      <form [formGroup]="formGroup" novalidate (submit)="submit()">
        <div class="form-header">
          <div class="title">
            <label>Újdonság {{addNew ? 'hozzáadás' : 'módosítás'}}</label>
          </div>
          <div class="id" *ngIf="newsfeedId">
            <label>ID: {{newsfeedId}}</label>
          </div>
        </div>
        <div class="form-details">
          <div class="details-row first-row">
            <mat-form-field class="newsfeed-title">
              <mat-label>Cím</mat-label>
              <input matInput type="text" autocomplete="off" formControlName="title"/>
            </mat-form-field>
            <app-search-bar class="series-search" [options]="seriesOptions" [header]="'Sorozat'" [width]="'100%'" (searchValue)="captureSeriesValue($event)" (selectedValue)="autocompleteSeriesValue($event)"></app-search-bar>
          </div>
          <div class="details-row" *ngIf="series">
            <label class="series-col">Sorozat címe: {{series.title}}</label>
            <label class="series-col">Sorozat megjelenése: {{series.prodYear}}</label>
          </div>
          <div class="details-row">
            <mat-form-field class="description">
              <mat-label>Leírás</mat-label>
              <textarea rows="6" matInput formControlName="description"></textarea>
            </mat-form-field>
          </div>
        </div>
        <button class="form-button" type="submit" mat-raised-button [disabled]="!isValid()">Mentés</button>
        <button class="form-button" type="button" mat-raised-button color="warn" *ngIf="!addNew" (click)="remove()">Törlés</button>
      </form>
  </div>
</div>

// react-app/src/pages/handlers/newsfeed-handler/NewsfeedHandler.tsx
import { Button, TextField } from '@mui/material';
import { AxiosError } from 'axios';
import { useCallback, useContext, useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Confirmation } from '../../../components/items/confirmation/Confirmation';
import { SearchBar } from '../../../components/items/search-bar/SearchBar';
import { SnackbarContext } from '../../../contexts/snackbarContext';
import { AutoCompleteItem } from '../../../models/menu.model';
import { Newsfeed } from '../../../models/newsfeed.model';
import { deleteNewsfeedRequest, getNewsfeedRequest, getNewsfeedsRequest, saveNewsfeedRequest, updateNewsfeedRequest } from '../../../utils/newsfeed-utils';
import { getSeriesesRequest, getSeriesRequest } from '../../../utils/series-utils';
import * as yup from 'yup';
import styles from './NewsfeedHandler.module.css';

type NewsfeedFormState = {
  id?: number;
  title: string;
  description: string;
  series?: {
    id: number;
    title: string;
    prodYear: number;
  }
}

type NewsfeedFormErrorMessage = {
  [key in keyof NewsfeedFormState]?: string;
}

export const NewsfeedHandler = () => {
  const [addNew, setAddNew] = useState(true);
  const [searchNewsfeedValue, setSearchNewsfeedValue] = useState("");
  const [searchSeriesValue, setSearchSeriesValue] = useState("");
  const [autocompleteOptions, setAutocompleteOptions] = useState<AutoCompleteItem[]>([]);
  const [autocompleteSeriesOptions, setAutocompleteSeriesOptions] = useState<AutoCompleteItem[]>([]);
  const [newsfeedId, setNewsfeedId] = useState<number | undefined>(undefined);
  const [newsfeed, setNewsfeed] = useState<Newsfeed | undefined>(undefined);
  const [formState, setFormState] = useState<NewsfeedFormState>(formInit);
  const [errorMsg, setErrorMsg] = useState<NewsfeedFormErrorMessage>({});
  const [openConfirmation, setOpenConfirmation] = useState(false);
  const navigate = useNavigate();
  const { id } = useParams();
  const { setMessage } = useContext(SnackbarContext);

  const submit = async (e: any) => {
    e.preventDefault();
    const errorMsg: NewsfeedFormErrorMessage = {} as NewsfeedFormErrorMessage;
    try {
      const result = await NewsfeedSchema.validate(formState, { abortEarly: false });
      const updatableNewsfeed: Newsfeed = {} as Newsfeed;

      if(newsfeedId) {
        if(result.title !== newsfeed.title) {
          updatableNewsfeed.title = result.title;
        }
        if(result.description !== newsfeed.description) {
          updatableNewsfeed.description = result.description;
        }
        if(result.series.id !== newsfeed.series.id) {
          updatableNewsfeed.series = {
            id: result.series.id,
            title: result.series.title,
            prodYear: result.series.prodYear
          } ;
        }

        const response = await updateNewsfeedRequest(newsfeedId, updatableNewsfeed);
        if(response) {
          setMessage(response, "success");
        }
      } else {
        updatableNewsfeed.title = result.title;
        updatableNewsfeed.description = result.description;
        updatableNewsfeed.series = {
          id: result.series.id,
          title: result.series.title,
          prodYear: result.series.prodYear
        };

        const response = await saveNewsfeedRequest(updatableNewsfeed);
        if(response) {
          setMessage("Sikeres újdonság felvitel!", "success");
          resetValues();
        }
      }

      setErrorMsg(errorMsg);
    } catch(err) {
      if(err instanceof yup.ValidationError) {
        for(const error of err.inner) {
          errorMsg[(error.path as keyof NewsfeedFormState)] = error.message;
        }
        setErrorMsg(errorMsg);
      } else {
        if((err as AxiosError<any>).response.status === 401) {
          navigate("/logout");
        }
        setMessage((err as AxiosError<any>).response.data.message)
      }
    }
  }

  const setSearchValueWrapper = (searchValue: string) => {
    setSearchNewsfeedValue(searchValue);
  }
  const setSeriesSearchValueWrapper = (searchValue: string) => {
    setSearchSeriesValue(searchValue);
  }
  const setAutocompleteValue = (newsfeedId: number) => {
    navigate(`/admin/newsfeed/${newsfeedId}`)
  }
  const setAutocompleteSeriesValue = async (seriesId: number) => {
    try {
      const response = await getSeriesRequest(seriesId);
      if(response) {
        setFormState((pre) => ({
          ...pre,
          series: {
            id: response.id,
            title: response.title,
            prodYear: response.prodYear,
          }
        }));
      }
    } catch(err) {
      if((err as AxiosError<any>).response.status === 401) {
        navigate("/logout");
      }
      setMessage((err as AxiosError<any>).response.data.message)
    }
  }
  
  const resetValues = () => {
    setNewsfeedId(undefined)
    setNewsfeed(undefined);
    setFormState(formInit);
    setErrorMsg({});
    setSearchSeriesValue("");
    setSearchNewsfeedValue("");
    setAutocompleteOptions([]);
    setAutocompleteSeriesOptions([]);
  }
  const handleFieldChange = (e: any, fieldName: string) => {
    setFormState((pre) => ({
      ...pre,
      [fieldName]: e.target.value,
    }));
  }
  const deleteNewsfeed = async () => {
    const resp = await deleteNewsfeedRequest(newsfeedId);
    if(resp) {
      setMessage(resp, "success");
      navigate("/newsfeed");
    }
  }

  const fetchNewsfeedData = useCallback(async () => {
    try {
      const response = await getNewsfeedRequest(newsfeedId);
      if(response) {
        setNewsfeed(response);
        setFormState({
          id: response.id,
          title: response.title,
          description: response.description,
          series: response.series,
        })
      }
    } catch(err) {
      if((err as AxiosError<any>).response.status === 401) {
        navigate("/logout");
      }
      setMessage((err as AxiosError<any>).response.data.message)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [newsfeedId]);
  const fetchNewsfeedsDataAndMakeOptions = useCallback(async () => {
    try {
      const response = await getNewsfeedsRequest(1, 10, searchNewsfeedValue);
      if(response) {
        setAutocompleteOptions(response.newsfeeds.map((newsfeed) => ({ value: newsfeed.id, label: `${newsfeed.id}, ${newsfeed.title} | ${newsfeed.series.title}`}) as AutoCompleteItem));
      }
    } catch(err) {
      if((err as AxiosError<any>).response.status === 401) {
        navigate("/logout");
      }
      setMessage((err as AxiosError<any>).response.data.message)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [searchNewsfeedValue]);
  const fetchSeriesesDataAndMakeOptions = useCallback(async () => {
    try {
      const response = await getSeriesesRequest(1, 10, searchSeriesValue);
      if(response) {
        setAutocompleteSeriesOptions(response.serieses.map((series) => ({ value: series.id, label: `${series.id}, ${series.title} | ${series.prodYear}`}) as AutoCompleteItem));
      }
    } catch(err) {
      if((err as AxiosError<any>).response.status === 401) {
        navigate("/logout");
      }
      setMessage((err as AxiosError<any>).response.data.message)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [searchSeriesValue]);

  useEffect(() => {
    fetchSeriesesDataAndMakeOptions();
  }, [searchSeriesValue, fetchSeriesesDataAndMakeOptions]);
  useEffect(() => {
    fetchNewsfeedsDataAndMakeOptions();
  }, [searchNewsfeedValue, fetchNewsfeedsDataAndMakeOptions]);
  useEffect(() => {
    if(!isNaN(Number(id))) {
      setAddNew(false);
      setNewsfeedId(Number(id));
    }
  }, [id]);
  useEffect(() => {
    if(newsfeedId) {
      fetchNewsfeedData();
    }
  }, [newsfeedId, fetchNewsfeedData]);

  const routeTo = (type: string) => {
    switch (type) {
      case "new":
        setAddNew(true);
        resetValues();
        navigate("/admin/newsfeed", { replace: true });
        return;
      case "change":
        setAddNew(false);
        resetValues();
        navigate("/admin/newsfeed", { replace: true });
        return;
      default:
        return;
    }
  }

  return (
    <div>
      <Confirmation open={openConfirmation} question="Biztos, hogy törlöd az újdonságot?" handleClose={() => setOpenConfirmation(false)} onAccept={deleteNewsfeed}/>
      <div className={styles["sub-navbar"]}>
        <label onClick={() => routeTo('new')} className={styles["sub-navbar-item"]}>Új hozzáadás</label>
        <label onClick={() => routeTo('change')} className={styles["sub-navbar-item"]}>Módosítás</label>
      </div>
      <div className={styles["container"]}>
        {
          !addNew &&
          <div className={styles["search"]}>
            <SearchBar options={autocompleteOptions} setSearchValue={setSearchValueWrapper} setAutocompleteValue={setAutocompleteValue}/>
          </div>
        }
        {(addNew || newsfeedId) &&
        <div className={styles["form-container"]}>
          <form onSubmit={submit}>
            <div className={styles["form-header"]}>
              <div className={styles["title"]}>
                <label>Újdonság {addNew ? 'hozzáadás' : 'módosítás'}</label>
              </div>
              {newsfeedId &&
              <div className={styles["id"]}>
                <label>ID: {newsfeedId}</label>
              </div>}
            </div>
            <div className={styles["form-details"]}>
              <div className={`${styles["details-row"]} ${styles["first-row"]}`}>
                <div className={styles["newsfeed-title"]}>
                  <TextField label="Cím" variant='standard' autoComplete='off' InputLabelProps={{ style:{transformOrigin: "50%" }}}
                    value={formState.title} onChange={(e) => handleFieldChange(e, "title")}
                    error={errorMsg.title !== undefined} helperText={errorMsg.title}
                  />
                </div>
                <SearchBar className={styles["series-search"]} options={autocompleteSeriesOptions} header="Sorozat"
                    setSearchValue={setSeriesSearchValueWrapper} setAutocompleteValue={setAutocompleteSeriesValue} 
                    width='100%' 
                />
              </div>
              {formState.series &&
              <div className={styles["details-row"]}>
                <label className={styles["series-col"]}>Sorozat címe: {formState.series.title}</label>
                <label className={styles["series-col"]}>Sorozat megjelenése: {formState.series.prodYear}</label>
              </div>}
              <div className={styles["details-row"]}>
                <div className={styles["description"]}>
                  <TextField label="Leírás" variant='standard' autoComplete='off' multiline minRows={6} InputLabelProps={{ style:{transformOrigin: "50%" }}}
                    value={formState.description} onChange={(e) => handleFieldChange(e, "description")}
                    error={errorMsg.description !== undefined} helperText={errorMsg.description}
                  />
                </div>
              </div>
            </div>
            <div className={styles["button-container"]}>
            <Button className={styles["form-button"]} type="submit" variant="contained" disabled={!NewsfeedSchema.isValidSync(formState)}>Mentés</Button>
            {!addNew &&
              <Button className={styles["form-button"]} type="button" variant="contained" color="error"
                  onClick={() => setOpenConfirmation(true)}
              >
                Törlés
              </Button>}
            </div>
          </form>
        </div>}
      </div>
    </div>
  )
}

const NewsfeedSchema = yup.object().shape({
  id: yup.number().min(1),
  title: yup.string().required("Cím megadása kötelező!"),
  description: yup.string().required("Leírás megadása kötelező!"),
  series: yup.object({
    id: yup.number(),
    title: yup.string(),
    prodYear: yup.number(),
  }).required("Sorozat megadása kötelező!"),
});

const formInit: NewsfeedFormState = {
  id: undefined,
  title: "",
  description: "",
  series: undefined,
}
