// react-app/src/pages/handlers/series-handler/SeriesHandler.tsx
import { Button, TextField } from '@mui/material';
import { AxiosError } from 'axios';
import { useCallback, useContext, useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { SearchBar } from '../../../components/items/search-bar/SearchBar';
import { SnackbarContext } from '../../../contexts/snackbarContext';
import { UploadableFile } from '../../../models/image.model';
import { AutoCompleteItem, DropdownItem } from '../../../models/menu.model';
import { Category, Season, Series } from '../../../models/series.model';
import { getCategoriesRequest } from '../../../utils/category-utils';
import { getSeriesesRequest, getSeriesRequest, saveSeriesRequest } from '../../../utils/series-utils';
import * as yup from 'yup';
import styles from './SeriesHandler.module.css';
import { DropdownBar } from '../../../components/items/drop-down-bar/DropdownBar';

type SeriesFormState = {
  id?: number;
  title: string;
  length: number | string;
  prodYear: number | string;
  ageLimit: number | string;
  seasons: Season[];
  categories: Category[];
  image?: UploadableFile;
}

type TempSeason = {
  season: number | string;
  episode: number | string;
}

type SeriesFormErrorMessage = {
  [key in keyof SeriesFormState]?: string;
}

type TempSeasonErrorMessage = {
  [key in keyof TempSeason]?: string;
}

export const SeriesHandler = () => {
  const [addNew, setAddNew] = useState(true);
  const [searchValue, setSearchValue] = useState("");
  const [autocompleteOptions, setAutocompleteOptions] = useState<AutoCompleteItem[]>([]);
  const [seriesId, setSeriesId] = useState<number | undefined>(undefined);
  const [series, setSeries] = useState<Series | undefined>(undefined);
  const [categories, setCategories] = useState<Category[]>([]);
  const [tempSeason, setTempSeason] = useState<TempSeason>(initSeason);
  const [removableSeasons, setRemovableSeasons] = useState<Season[]>([]);
  const [formState, setFormState] = useState<SeriesFormState>(formInit);
  const [errorMsg, setErrorMsg] = useState<SeriesFormErrorMessage>({});
  const [errorSeasonMsg, setErrorSeasonMsg] = useState<TempSeasonErrorMessage>({});
  const navigate = useNavigate();
  const { id } = useParams();
  const { setMessage } = useContext(SnackbarContext);

  const submit = async (e: any) => {
    e.preventDefault();
    const errorMsg: SeriesFormErrorMessage = {} as SeriesFormErrorMessage;

    try {
      const result = await SeriesSchema.validate(formState);
      let saveSeries: Series = {} as Series;
      /**
       * kép objektum hozzáaása
       */
      if(!seriesId) {
        saveSeries = {
          title: result.title,
          ageLimit: result.ageLimit,
          length: result.length,
          prodYear: result.prodYear,
          seasons: result.seasons,
          categories: result.categories,
        } //TODO: kép hozzáadás
        const response = await saveSeriesRequest(saveSeries);
        if(response) {
          resetValues();
          setMessage("Sikeres sorozat hozzáadás!", "success");
        }
      } else {
        //Meglévő módosítása
      }

      setErrorMsg(errorMsg);
    } catch(err) {
      if(err instanceof yup.ValidationError) {
        for(const error of err.inner) {
          errorMsg[(error.path as keyof SeriesFormState)] = error.message;
        }
        setErrorMsg(errorMsg);
      } else {
        if((err as AxiosError<any>).response.status === 401) {
          navigate("/logout");
        }
        setMessage((err as AxiosError<any>).response.data.message)
      }
    }

    console.log(formState);

  }
  const saveSeason = () => {
    if(tempSeason.season && tempSeason.episode) {
      const seasonArray: Season[] = formState.seasons;
      const newSeason: Season = { season: Number(tempSeason.season), episode: Number(tempSeason.episode) }

      let index = -1;
      let i = 0;
      for(const season of seasonArray) {
        if(season.season === newSeason.season) {
          index = i;
          newSeason.id = season.id;
          break;
        }
        i++;
      }

      if(index === -1) {
        seasonArray.push(newSeason);
      } else {
        seasonArray[index] = newSeason;
      }

      resetSeasonValues();
      setFormState((pre) => ({
        ...pre,
        seasons: seasonArray
      }));
    } else {
      const errorSeasonMessage: TempSeasonErrorMessage = {};
      if(!tempSeason.season) {
        errorSeasonMessage.season = "Kötelező az évad megadása!"
      }
      if(!tempSeason.episode) {
        errorSeasonMessage.episode = "Kötelező az epizód megadása!"
      }
      setErrorSeasonMsg(errorSeasonMessage)
    }
  }
  const removeSeason = (season: number) => {
    if(!season) {
      return;
    }

    const seasonArray: Season[] = formState.seasons.filter((sn: Season) => {
      if(sn.season === season) {
        if(sn.id) {
          setRemovableSeasons((pre) => ([
            ...pre,
            { id: sn.id} as Season
          ]))
        }
        return false;
      }
      return true;
    });
    setFormState((pre) => ({
      ...pre,
      seasons: seasonArray
    }));
  }

  const setSearchValueWrapper = (searchValue: string) => {
    setSearchValue(searchValue);
  }
  const setAutocompleteValue = (seriesId: number) => {
    navigate(`/admin/series/${seriesId}`)
  }

  const resetValues = () => {
    setSearchValue("");
    setAutocompleteOptions([]);
    setSeriesId(undefined);
    setSeries(undefined);
    setFormState(formInit);
    setErrorMsg({});
  }
  const resetSeasonValues = () => {
    setTempSeason(initSeason);
    setErrorSeasonMsg({});
  }
  const handleFieldChange = (e: any, fieldName: string) => {
    setFormState((pre) => ({
      ...pre,
      [fieldName]: e.target.value,
    }));
  }
  const handleTempSeasonChange = (e: any, fieldName: string) => {
    setTempSeason((pre) => ({
      ...pre,
      [fieldName]: e.target.value,
    }));
  }
  const isTempSeasonValuesValid = () => {
    if(!tempSeason.season || tempSeason.season < 1) {
      return false;
    }
    if(!tempSeason.episode || tempSeason.episode < 1) {
      return false
    }

    return true;
  }
  const getCategoryOptions = useCallback(() => {
    if(!categories || categories.length < 1) {
      return [];
    }

    return categories.map((category) => {
      if(formState.categories.find((ct) => ct.id === category.id)) {
        return {
          shownValue: category.name,
          value: category.id,
          highlight: true
        } as DropdownItem;
      }
      return {
        shownValue: category.name,
        value: category.id
      } as DropdownItem;
    }) 
  }, [formState.categories, categories]);
  const handleCategory = (id: number) => {
    if(!id) {
      return;
    }

    const categoryArray: Category[] = formState.categories ?? [];
    if(categoryArray.find((category) => category.id === id)) {
      setFormState((pre) => ({
        ...pre,
        categories: categoryArray.filter((ct) => ct.id !== id)
      }));
    } else {
      const category = categories.find((ct) => ct.id === id);
      setFormState((pre) => ({
        ...pre,
        categories: [...categoryArray, category]
      }));
    }
  }
  const getSeasonOptions = useCallback(() => {
    if(formState.seasons) {
      return formState.seasons.sort((a: Season, b: Season) => a.season - b.season).map((season: Season) => ({
        value: season.season,
        shownValue: `${season.season}. évad, ${season.episode} rész`
      }) as DropdownItem)
    }

    return [];
  }, [formState.seasons]);

  const fetchSeriesData = useCallback(async () => {
    try {
      const response = await getSeriesRequest(seriesId);
      if(response) {
        setSeries(response);
        setFormState({
          ...response
        })
      }
    } catch(err) {
      if((err as AxiosError<any>).response.status === 401) {
        navigate("/logout");
      }
      setMessage((err as AxiosError<any>).response.data.message)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [seriesId]);
  const fetchSeriesesDataAndMakeOptions = useCallback(async () => {
    try {
      const response = await getSeriesesRequest(1, 10, searchValue);
      if(response) {
        setAutocompleteOptions(response.serieses.map((series) => ({ value: series.id, label: `${series.id}, ${series.title} | ${series.prodYear}`}) as AutoCompleteItem));
      }
    } catch(err) {
      if((err as AxiosError<any>).response.status === 401) {
        navigate("/logout");
      }
      setMessage((err as AxiosError<any>).response.data.message)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [searchValue]);
  const fetchCategoriesData = async () => {
    try {
      const response = await getCategoriesRequest();
      if(response) {
        setCategories(response);
      }
    } catch(err) {
      if((err as AxiosError<any>).response.status === 401) {
        navigate("/logout");
      }
      setMessage((err as AxiosError<any>).response.data.message)
    }
  }

  useEffect(() => {
    fetchSeriesesDataAndMakeOptions();
  }, [searchValue, fetchSeriesesDataAndMakeOptions]);
  useEffect(() => {
    if(seriesId) {
      fetchSeriesData();
    }
  }, [seriesId, fetchSeriesData]);
  useEffect(() => {
    if(!isNaN(Number(id))) {
      setAddNew(false);
      setSeriesId(Number(id));
    }
  }, [id]);
  useEffect(() => {
    fetchCategoriesData();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const routeTo = (type: string) => {
    switch (type) {
      case "new":
        setAddNew(true);
        resetValues();
        navigate("/admin/series", { replace: true });
        return;
      case "change":
        setAddNew(false);
        resetValues();
        navigate("/admin/series", { replace: true });
        return;
      default:
        return;
    }
  }

  return (
    <div>
      <div className={styles["sub-navbar"]}>
        <label onClick={() => routeTo('new')} className={styles["sub-navbar-item"]}>Új hozzáadás</label>
        <label onClick={() => routeTo('change')} className={styles["sub-navbar-item"]}>Módosítás</label>
      </div>
      <div className={styles["container"]}>
        {!addNew &&
        <div className={styles["search"]}>
          <SearchBar options={autocompleteOptions} setSearchValue={setSearchValueWrapper} setAutocompleteValue={setAutocompleteValue}/>
        </div>}
        {(addNew || seriesId) &&
        <div className={styles["form-container"]}>
          <form onSubmit={submit}>
            <div className={styles["form-header"]}>
              <div className={styles["title"]}>
                <label>Sorozat {addNew ? 'hozzáadás' : 'módosítás'}</label>
              </div>
              {seriesId &&
              <div className={styles["id"]}>
                <label>ID: {seriesId}</label>
              </div>}
            </div>
            <div className={styles["form-details"]}>
              <div className={styles["details-row"]}>
                <div className={styles["details-column"]}>
                  <div className={styles["form-field"]}>
                    <TextField label="Cím" variant='standard' autoComplete='off' InputLabelProps={{ style:{transformOrigin: "50%" }}}
                      value={formState.title} onChange={(e) => handleFieldChange(e, "title")}
                      error={errorMsg.title !== undefined} helperText={errorMsg.title}
                    />
                  </div>
                </div>
                <div className={styles["details-column"]}>
                  <div className={styles["form-field"]}>
                    <TextField label="Hossza" variant='standard' type='number' autoComplete='off' InputLabelProps={{ style:{transformOrigin: "50%" }}}
                      value={formState.length} onChange={(e) => handleFieldChange(e, "length")}
                      error={errorMsg.length !== undefined} helperText={errorMsg.length}
                    />
                  </div>
                </div>
              </div>
              <div className={styles["details-row"]}>
                <div className={styles["details-column"]}>
                  <div className={styles["form-field"]}>
                    <TextField label="Megjelenési év" variant='standard' type='number' autoComplete='off' InputLabelProps={{ style:{transformOrigin: "50%" }}}
                      value={formState.prodYear} onChange={(e) => handleFieldChange(e, "prodYear")}
                      error={errorMsg.prodYear !== undefined} helperText={errorMsg.prodYear}
                    />
                  </div>
                </div>
                <div className={styles["details-column"]}>
                <div className={styles["form-field"]}>
                    <TextField label="Korhatár" variant='standard' type='number' autoComplete='off' InputLabelProps={{ style:{transformOrigin: "50%" }}}
                      value={formState.ageLimit} onChange={(e) => handleFieldChange(e, "ageLimit")}
                      error={errorMsg.ageLimit !== undefined} helperText={errorMsg.ageLimit}
                    />
                  </div>
                </div>
              </div>
              <div className={styles["details-row"]}>
                <div className={styles["details-column"]}>
                  <div className={`${styles["form-field"]} ${styles["form-season-field"]}`}>
                    <div className={styles["season-field"]}>
                      <TextField label="Évad" variant='standard' InputProps={{ inputProps: { min: 1 } }} type='number' autoComplete='off' InputLabelProps={{ style:{transformOrigin: "50%" }}}
                        value={tempSeason.season} onChange={(e) => handleTempSeasonChange(e, "season")}
                        error={errorSeasonMsg.season !== undefined} helperText={errorSeasonMsg.season}
                      />
                    </div>
                    <div className={styles["season-field"]}>
                      <TextField label="Epizód" variant='standard' InputProps={{ inputProps: { min: 1 } }} type='number' autoComplete='off' InputLabelProps={{ style:{transformOrigin: "50%" }}}
                        value={tempSeason.episode} onChange={(e) => handleTempSeasonChange(e, "episode")}
                        error={errorSeasonMsg.episode !== undefined} helperText={errorSeasonMsg.episode}
                      />
                    </div>
                    <Button className={styles["season-button"]} type="button" variant="contained" color="success" onClick={saveSeason} disabled={!isTempSeasonValuesValid()}>
                      Mentés
                    </Button>
                  </div>
                </div>
                <div className={styles["details-column"]}>
                  <DropdownBar options={getCategoryOptions()} header='Kategóriák' width='100%'
                      changeHeader={false} action={true} setSelected={handleCategory}
                  />
                </div>
              </div>
              <div className={styles["details-row"]}>
                <div className={styles["details-column"]}>
                  <DropdownBar options={getSeasonOptions()} header="Évadok" width='100%'
                      changeHeader={false} action={true} setSelected={removeSeason}
                  />
                </div>
                <div className={`${styles["details-column"]} ${styles["form-season-field"]}`}>
                  <input hidden name="image" type="file" id="fileInput" /> {/* (change)="uploadFile($event)" */}
                  {/* <button className={styles["image-button"]} mat-raised-button color="primary" type="button"> { (click)="fileInput.click()" }
                    selectedSeries && selectedSeries.image ? "Borítókép módosítás" : "Borítókép feltöltés"
                  </button> */}
                  {/* <button mat-icon-button title="Borítókép törlése" type="button"
                      *ngIf="selectedSeries && selectedSeries.image" color="warn"
                      (click)="removeImage()"
                  >
                    <mat-icon>delete</mat-icon>
                  </button> */}
                  <div>
                    {/* <mat-form-field className={styles["image-offset"]} title="Horizontális eltolás">
                      <mat-label>X</mat-label>
                      <input matInput autocomplete="off" [formControl]="xOffset"/>
                    </mat-form-field>
                    <mat-form-field className={styles["image-offset"]} title="Vertikális eltolás">
                      <mat-label>Y</mat-label>
                      <input matInput autocomplete="off" [formControl]="yOffset"/>
                    </mat-form-field> */}
                  </div>
                </div>
              </div>
            </div>
            <Button className={styles["form-button"]} variant="contained" type="submit" 
                disabled={!SeriesSchema.isValidSync(formState)}>
                  Mentés
            </Button>
          </form>
        </div>}
      </div>
    </div>
  )
}

const SeriesSchema = yup.object().shape({
  id: yup.number(),
  title: yup.string().required("Cím megadása kötelező!"),
  length: yup.number().required("Hossz megadása kötelező!").min(1, "Legalább 1 perc hosszúnak kell lennie!"),
  prodYear: yup.number().required("Kiadási éve megadása kötelező!").min(1900, "A kiadása legalább 1900 lehet!"),
  ageLimit: yup.number().required("Korhatár megadása kötelező!").min(1, "A korhatár alsóhatára 1 év!"),
  seasons: yup.array().optional(),
  categories: yup.array().optional()
});

const formInit: SeriesFormState = {
  id: undefined,
  title: "",
  length: "",
  prodYear: "",
  ageLimit: "",
  seasons: [],
  categories: [],
  image: undefined,
}

const initSeason: TempSeason = {
  season: "",
  episode: "",
}

// angular/src/app/pages/handlers/series-handler/series-handler.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';
import { MatSnackBar } from '@angular/material/snack-bar';
import { ActivatedRoute, Router } from '@angular/router';
import { TempUploadedImage, UploadableFile } from 'src/app/models/image.model';
import { DropdownItem, ErrorMessage } from 'src/app/models/menu.model';
import { Category, Season, Series } from 'src/app/models/series.model';
import { CategoryService } from 'src/app/services/category.service';
import { ImageService } from 'src/app/services/image.service';
import { SeriesService } from 'src/app/services/series.service';

@Component({
  selector: 'app-series-handler',
  templateUrl: './series-handler.component.html',
  styleUrls: ['./series-handler.component.css']
})
export class SeriesHandlerComponent implements OnInit {
  formGroup!: FormGroup;
  seasonControl!: FormControl;
  episodeControl!: FormControl;
  xOffset!: FormControl;
  yOffset!: FormControl;
  addNew: boolean;
  seriesId?: number;
  seriesOptions: DropdownItem[];
  selectedSeries?: Series;
  tempImage?: TempUploadedImage;
  private categories!: Category[];
  private removableSeasons: Season[];
  constructor(private fb: FormBuilder,
              private seriesService: SeriesService,
              private categoryService: CategoryService,
              private imageService: ImageService,
              private snackbar: MatSnackBar,
              private router: Router,
              private route: ActivatedRoute) {
    this.addNew = true;
    this.seriesOptions = [];
    this.removableSeasons = [];
  }

  async ngOnInit() {
    this.formGroup = this.fb.group({
      title: ["", [Validators.required]],
      length: ["", [Validators.required, Validators.min(1)]],
      prodYear: ["", [Validators.required, Validators.min(1900), Validators.max(2100)]],
      ageLimit: ["", [Validators.required, Validators.min(1), Validators.max(99)]],
      seasons: [[]],
      categories: [[]]
    });
    this.seasonControl = this.fb.control('', [Validators.min(1)]);
    this.episodeControl = this.fb.control('', [Validators.min(1)]);
    this.xOffset = this.fb.control('');
    this.yOffset = this.fb.control('');
    this.categories = await this.categoryService.getCategories();

    const tempId = this.route.snapshot.paramMap.get("id");
    if(tempId) {
      this.addNew = false;
      this.seriesId = Number(tempId);

      try {
        this.selectedSeries = await this.seriesService.getSeries(this.seriesId);
        this.setValues(this.selectedSeries);
      } catch(err) {
        this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
        this.router.navigateByUrl(`/admin/series`, { replaceUrl: true });
      }
    }
  }

  submit = async () => {
    if(!this.formGroup.valid) {
      return;
    }

    const formSeries: Series = {
      title: this.formGroup.get("title")?.value,
      prodYear: this.formGroup.get("prodYear")?.value,
      length: this.formGroup.get("length")?.value,
      ageLimit: this.formGroup.get("ageLimit")?.value,
      seasons: this.formGroup.get("seasons")?.value,
      categories: this.formGroup.get("categories")?.value,
    }
    if(this.tempImage) {
      formSeries.image = { ...this.tempImage };
      if(this.xOffset.value !== "" || this.xOffset.value !== undefined) {
        formSeries.image.x_offset = this.xOffset.value;
      }
      if(this.yOffset.value !== "" || this.yOffset.value !== undefined) {
        formSeries.image.y_offset = this.yOffset.value;
      }
    }

    if(this.addNew) {
      try {
        const response = await this.seriesService.saveSeries(formSeries);
        if(response) {
          this.snackbar.open("Sorozat sikeresen mentve!", 'X', { duration: 3000, verticalPosition: 'bottom', panelClass: ['snackbar-success'] });
        }
        this.resetValues();
      } catch(err) {
        this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
      }
    } else {
      const updateSeries: Series = {} as Series;

      if(formSeries.title !== this.selectedSeries?.title) {
        updateSeries.title = formSeries.title;
      }
      if(formSeries.prodYear !== this.selectedSeries?.prodYear) {
        updateSeries.prodYear = formSeries.prodYear;
      }
      if(formSeries.length !== this.selectedSeries?.length) {
        updateSeries.length = formSeries.length;
      }
      if(formSeries.ageLimit !== this.selectedSeries?.ageLimit) {
        updateSeries.ageLimit = formSeries.ageLimit;
      }
      if(formSeries.image) {
        updateSeries.image = formSeries.image;
      }
      if(!this.tempImage && this.selectedSeries?.image) {
        if(this.xOffset.value && this.selectedSeries.image.x_offset !== this.xOffset.value) {
          if(!updateSeries.image) {
            updateSeries.image = {
              id: this.selectedSeries?.image?.id,
              name: this.selectedSeries?.image?.name
            };
          }
          updateSeries.image.x_offset = this.xOffset.value;
        }
        if(this.yOffset.value && this.selectedSeries.image.y_offset !== this.yOffset.value) {
          if(!updateSeries.image) {
            updateSeries.image = {
              id: this.selectedSeries?.image?.id,
              name: this.selectedSeries?.image?.name
            };
          }
          updateSeries.image.y_offset = this.yOffset.value;
        }
      }
      if(this.selectedSeries?.categories && this.selectedSeries?.categories.length > 0) {
        updateSeries.categories = [];
        const categoryMap: Map<number, Category> = new Map<number, Category>();
        for(let ct of this.selectedSeries?.categories) {
          if(ct.id)
            categoryMap.set(ct.id, { ...ct, remove: true });
        }

        for(let category of formSeries.categories) {
          if(category.id)
            categoryMap.set(category.id, category);
        }

        categoryMap.forEach((value, id) => {
          updateSeries.categories.push(value);
        });

      } else if(formSeries.categories && formSeries.categories.length > 0) {
        updateSeries.categories = formSeries.categories
      }

      if(!this.selectedSeries?.seasons || this.selectedSeries?.seasons.length < 0) {
        updateSeries.seasons = formSeries.seasons;
      } else {
        updateSeries.seasons = [];

        for(let season of formSeries.seasons) {
          if((!season.id && season.season && season.episode)
          || (season.id && season.season && season.episode)) {
            updateSeries.seasons.push(season);
          }
        }
      }
      updateSeries.seasons.push(...this.removableSeasons);

      try {
        if(!this.seriesId) {
          this.snackbar.open("Hiányzó ID, nyisd meg újra a módosítandó sorozatot!", 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
          return;
        }
        const response = await this.seriesService.updateSeries(this.seriesId, updateSeries);
        if(response) {
          this.snackbar.open("Sorozat sikeresen módosítva!", 'X', { duration: 3000, verticalPosition: 'bottom', panelClass: ['snackbar-success'] });
          this.router.navigateByUrl("/series");
        }
      } catch(err) {
        this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
      }
    }
  }

  autocompleteValue = async (value: any) => {
    if(!isNaN(value)) {
      this.seriesId = value as number;
      await this.router.navigateByUrl(`/admin/series/${this.seriesId}`, { replaceUrl: true });
      try {
        this.setValues(await this.seriesService.getSeries(this.seriesId));
      } catch(err) {
        this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
      }
    }
  }

  captureValue = async (value: string) => {
    try {
      const response = await this.seriesService.getSerieses(1, 10, value);
      this.seriesOptions = response.serieses
      ? response.serieses
        .map((series) => ({
          value: series.id,
          shownValue: `${series.title}, ${series.prodYear}`
        }) as DropdownItem)
      : [];
    } catch(err) {
      this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
    }
  }

  uploadFile = async (fileEvent: any) => {
    const uploadableFile = fileEvent.target.files[0] ?? null;
    if(uploadableFile) {
      try {
        const response = await this.imageService.upload(uploadableFile)
        if(response) {
          this.tempImage = response;
          this.snackbar.open("Sikeres képfeltöltés", 'X', { duration: 3000, verticalPosition: 'bottom', panelClass: ['snackbar-success'] });
        }
      } catch(err) {
        this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
      }
    }
  }

  removeImage = async () => {
    if(this.selectedSeries && this.selectedSeries.id) {
      try {
        const response = await this.seriesService.deleteImage(this.selectedSeries.id);
        if(response) {
          this.resetImageValues();
          this.snackbar.open(response, 'X', { duration: 3000, verticalPosition: 'bottom', panelClass: ['snackbar-success'] });
        }
      } catch(err) {
        this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
      }
    }
  }

  saveSeason = () => {
    if(this.seasonControl.value && this.episodeControl.value) {
      const seasonArray: Season[] = this.formGroup.get("seasons")?.value;
      const newSeason: Season = { season: this.seasonControl.value, episode: this.episodeControl.value }

      let index = -1;
      let i = 0;
      for(const season of seasonArray) {
        if(season.season === this.seasonControl.value) {
          index = i;
          newSeason.id = season.id;
          break;
        }
        i++;
      }

      if(index === -1) {
        seasonArray.push(newSeason);
      } else {
        seasonArray[index] = newSeason;
      }

      this.seasonControl.setValue("");
      this.episodeControl.setValue("");
      this.seasonControl.markAsUntouched({ onlySelf: true });
      this.episodeControl.markAsUntouched({ onlySelf: true });
      this.formGroup.get("seasons")?.setValue(seasonArray);
    }
  }

  removeSeason = (season: number) => {
    if(!season) {
      return;
    }

    const seasonArray: Season[] = this.formGroup.get("seasons")?.value.filter((sn: Season) => {
      if(sn.season === season) {
        if(sn.id) {
          this.removableSeasons.push({ id: sn.id} as Season);
        }
        return false;
      }
      return true;
    });
    this.formGroup.get("seasons")?.setValue(seasonArray);
  }

  handleCategory = (id: number) => {
    if(!id) {
      return;
    }

    const categoryArray: Category[] = this.formGroup.get("categories")?.value ?? [];
    if(categoryArray.find((category) => category.id === id)) {
      this.formGroup.get("categories")?.setValue(categoryArray.filter((ct) => ct.id !== id));
    } else {
      const category = this.categories.find((ct) => ct.id === id);
      this.formGroup.get("categories")?.setValue([...categoryArray, category]);
    }


  }

  getSeasonOptions = () => {
    if(this.formGroup.get("seasons")?.value) {
      return this.formGroup.get("seasons")?.value.sort((a: Season, b: Season) => a.season - b.season).map((season: Season) => ({
        value: season.season,
        shownValue: `${season.season}. évad, ${season.episode} rész`
      }) as DropdownItem)
    }

    return [];
  }
  getCategoryOptions = () => {
    const formCategories: Category[] = this.formGroup.get("categories")?.value;
    if(!this.categories) {
      return [];
    }

    return this.categories.map((category) => {
      if(formCategories.find((ct) => ct.id === category.id)) {
        return {
          shownValue: category.name,
          value: category.id,
          highlight: true
        } as DropdownItem;
      }
      return {
        shownValue: category.name,
        value: category.id
      } as DropdownItem;
    });
  }

  resetValues = () => {
    this.selectedSeries = undefined;
    this.seriesId = undefined;
    this.seriesOptions = [];
    this.removableSeasons = [];
    this.tempImage = undefined;

    this.seasonControl.setValue("");
    this.episodeControl.setValue("");
    this.formGroup.setValue({
      title: "",
      length: "",
      prodYear: "",
      ageLimit: "",
      seasons: [],
      categories: []
    });
    this.resetImageValues();
  }

  resetImageValues = () => {
    if(this.selectedSeries) {
      this.selectedSeries.image = undefined;
    }
    this.tempImage = undefined;
    this.xOffset.setValue("");
    this.yOffset.setValue("");
  }

  setValues = (series: Series) => {
    this.formGroup.setValue({
      title: series.title,
      length: series.length,
      prodYear: series.prodYear,
      ageLimit: series.ageLimit,
      seasons: series.seasons,
      categories: series.categories
    });

    if(series.image) {
      if(series.image.x_offset) {
        this.xOffset.setValue(series.image.x_offset);
      }
      if(series.image.y_offset) {
        this.yOffset.setValue(series.image.y_offset);
      }
    }
  }

  routeTo = (type: string) => {
    switch (type) {
      case "new":
        this.addNew = true;
        this.resetValues();
        this.router.navigateByUrl("/admin/series", { replaceUrl: true });
        return;
      case "change":
        this.addNew = false;
        this.resetValues();
        this.router.navigateByUrl(`/admin/series`, { replaceUrl: true });
        return;
      default:
        return;
    }
  }
}

<div>
  <div class="sub-navbar">
    <a (click)="routeTo('new')" class="sub-navbar-item">Új hozzáadás</a>
    <a (click)="routeTo('change')" class="sub-navbar-item">Módosítás</a>
  </div>
  <div class="container">
    <div class="search" *ngIf="!addNew">
      <app-search-bar [options]="seriesOptions" (searchValue)="captureValue($event)" (selectedValue)="autocompleteValue($event)"></app-search-bar>
    </div>
    <div class="form-container" *ngIf="addNew || selectedSeries">
      <form [formGroup]="formGroup" novalidate (submit)="submit()">
        <div class="form-header">
          <div class="title">
            <label>Sorozat {{addNew ? 'hozzáadás' : 'módosítás'}}</label>
          </div>
          <div class="id" *ngIf="seriesId">
            <label>ID: {{seriesId}}</label>
          </div>
        </div>
        <div class="form-details">
          <div class="details-row">
            <div class="details-column">
              <mat-form-field class="form-field">
                <mat-label>Cím</mat-label>
                <input matInput type="text" autocomplete="off" formControlName="title"/>
                <mat-error>Hibás mező!</mat-error>
              </mat-form-field>
            </div>
            <div class="details-column">
              <mat-form-field class="form-field">
                <mat-label>Hossza</mat-label>
                <input matInput type="number" autocomplete="off" formControlName="length"/>
                <mat-error>Hibás mező!</mat-error>
              </mat-form-field>
            </div>
          </div>
          <div class="details-row">
            <div class="details-column">
              <mat-form-field class="form-field">
                <mat-label>Megjelenési év</mat-label>
                <input matInput type="number" min="1900" autocomplete="off" formControlName="prodYear"/>
                <mat-error>Hibás mező!</mat-error>
              </mat-form-field>
            </div>
            <div class="details-column">
              <mat-form-field class="form-field">
                <mat-label>Korhatár</mat-label>
                <input matInput type="number" min="1" autocomplete="off" formControlName="ageLimit"/>
                <mat-error>Hibás mező!</mat-error>
              </mat-form-field>
            </div>
          </div>
          <div class="details-row">
            <div class="details-column">
              <div class="form-field form-season-field">
                <mat-form-field class="season-field">
                  <mat-label>Évad</mat-label>
                  <input matInput type="number" min="1" autocomplete="off" [formControl]="seasonControl"/>
                  <mat-error>Hibás mező!</mat-error>
                </mat-form-field>
                <mat-form-field class="season-field">
                  <mat-label>Epizód</mat-label>
                  <input matInput type="number" min="1" autocomplete="off" [formControl]="episodeControl"/>
                  <mat-error>Hibás mező!</mat-error>
                </mat-form-field>
                <button class="season-button" mat-raised-button color="primary" type="button" (click)="saveSeason()" [disabled]="!seasonControl.valid || !episodeControl.valid">
                  Mentés
                </button>
              </div>
            </div>
            <div class="details-column">
              <app-drop-down-bar class="form-field" [header]="'Kategóriák'" [width]="'100%'" [changeHeader]="false" [action]="true" [options]="getCategoryOptions()" (selected)="handleCategory($event)"></app-drop-down-bar>
            </div>
          </div>
          <div class="details-row">
            <div class="details-column">
              <app-drop-down-bar class="form-field" [header]="'Évadok'" [width]="'100%'" [changeHeader]="false" [action]="true" [options]="getSeasonOptions()" (selected)="removeSeason($event)"></app-drop-down-bar>
            </div>
            <div class="details-column form-season-field">
              <input hidden (change)="uploadFile($event)" name="image" type="file" #fileInput />
              <button class="image-button" mat-raised-button color="primary" type="button" (click)="fileInput.click()">
                {{selectedSeries && selectedSeries.image ? "Borítókép módosítás" : "Borítókép feltöltés"}}
              </button>
              <button mat-icon-button title="Borítókép törlése" type="button"
                  *ngIf="selectedSeries && selectedSeries.image" color="warn"
                  (click)="removeImage()"
              >
                <mat-icon>delete</mat-icon>
              </button>
              <div *ngIf="tempImage || (selectedSeries && selectedSeries.image)">
                <mat-form-field class="image-offset" title="Horizontális eltolás">
                  <mat-label>X</mat-label>
                  <input matInput autocomplete="off" [formControl]="xOffset"/>
                </mat-form-field>
                <mat-form-field class="image-offset" title="Vertikális eltolás">
                  <mat-label>Y</mat-label>
                  <input matInput autocomplete="off" [formControl]="yOffset"/>
                </mat-form-field>
              </div>
            </div>
          </div>
        </div>
        <button class="form-button" mat-raised-button [disabled]="!formGroup.valid">Mentés</button>
      </form>
    </div>
  </div>
</div>
