// react-app/src/components/items/userseries-item/UserseriesItem.tsx
import { Icon, IconButton } from '@mui/material';
import { FC, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { UserSeries } from '../../../models/series.model';
import { User } from '../../../models/user.model';
import { hasRight } from '../../../utils/auth-utils';
import { getDefaultImageUrl, getImageUrlRequest } from '../../../utils/image-utils';
import { getCategories, getLimitColor } from '../../../utils/series-utils';
import styles from './UserseriesItem.module.css';

type UserSeriesItemProps = {
  userseries: UserSeries,
  user?: User,
}

type UserSeriesItemState = {
  canEdit: boolean;
}

export const UserseriesItem: FC<UserSeriesItemProps> = ({ userseries, user }) => {
  const [categories] = useState<string>(getCategories(userseries.series));
  const [state, setState] = useState<UserSeriesItemState>({ canEdit: false });
  const [image, setImage] = useState<{ url: string, isDefault: boolean}>({ url: "", isDefault: true });
  const navigate = useNavigate();

  const editSeries = () => {
    navigate(`/user/handle/series/${userseries.series.id}`);
  }

  useEffect(() => {
    if(userseries.series.image?.name) {
      getImageUrlRequest(userseries.series.image?.name)
        .then((url) => {
          setImage({ url: url, isDefault: false});          
        })
        .catch((url) => {
          setImage({ url: url, isDefault: true});
        });
    } else {
      setImage({ url: getDefaultImageUrl(), isDefault: true});
    }
  }, [userseries]);

  useEffect(() => {
    const tempState: UserSeriesItemState = {} as UserSeriesItemState;
    tempState.canEdit = hasRight(["user"], user);
    setState(tempState);
  }, [user]);

  return (
    <div className={`${styles["series-item"]} ${image.isDefault ? styles["defaultImage"] : ""}`}
        style={{
          backgroundImage: `url(${image.url})`,
          backgroundPosition: `top ${userseries.series.image?.y_offset} left ${userseries.series.image?.x_offset}`
        }}
    >
        <div className={styles["float-button"]}>
          {state.canEdit &&
            <IconButton onClick={editSeries}>
            <Icon fontSize='small' className={styles["float-icon"]}>build</Icon>
          </IconButton>}
        </div>
      <header>
        <label className={styles["series-name"]}>{userseries.series.title}</label>
      </header>
      <div className={styles['series-item-body']}>
        <div className={styles["seasons"]}>{userseries.season}. évad, {userseries.episode}. rész</div>
        <div className={styles["series-prodyear"]}>{userseries.series.prodYear}</div>
        <div className={styles["series-length"]}>{userseries.series.length} perc</div>
        <div className={styles["series-category"]}>{categories}</div>
      </div>
      <footer>
        <label className={styles["age-limit"]} style={{ borderColor: getLimitColor(userseries.series.ageLimit)}}>{userseries.series.ageLimit}</label>
        <div className={styles["status"]}>
          <label>{userseries.status.name}</label>
        </div>
      </footer>
    </div>
  )
}

// angular/src/app/components/items/userseries-item/userseries-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { UserSeries } from 'src/app/models/series.model';
import { AuthService } from 'src/app/services/auth.service';
import { ImageService } from 'src/app/services/image.service';

@Component({
  selector: 'app-userseries-item',
  templateUrl: './userseries-item.component.html',
  styleUrls: ['./userseries-item.component.css']
})
export class UserseriesItemComponent implements OnInit {
  @Input() userseries!: UserSeries;
  canEdit: boolean;
  imageUrl: string;
  offset: { x: string, y: string };
  constructor(private router: Router,
              private authService: AuthService,
              public imageService: ImageService) {
    this.canEdit = false;
    this.imageUrl = "";
    this.offset = { x: '25px', y: '-10px'};
  }

  async ngOnInit() {
    this.canEdit = this.authService.hasRight(['user']);
    if(this.userseries.series.image) {
      this.imageUrl = await this.imageService.getImageUrl(this.userseries.series.image?.name);
      this.offset = {
        x: this.userseries.series.image.x_offset as string,
        y: this.userseries.series.image.y_offset as string
      };
    } else {
      this.imageUrl = this.imageService.getDefaultImageUrl();
    }
  }

  getCategories = (): string => {
    if(!this.userseries.series.categories) {
      return "";
    }
    return this.userseries.series.categories.map((category) => category.name).join(', ');
  }

  getLimitColor = (): string => {
    if(!this.userseries.series || this.userseries.series.ageLimit >= 18) {
      return 'var(--red)';
    }

    if(this.userseries.series.ageLimit >= 16) {
      return '#F19F24'
    }

    if(this.userseries.series.ageLimit >= 12) {
      return '#FCFF5A'
    }

    return '#51D911'
  }

  editSeries = () => {
    this.router.navigateByUrl(`/user/handle/series/${this.userseries.series.id}`);
  }
}

<div class="series-item" [ngStyle]="{'background-image': 'url('+imageUrl+')',
    'background-position': 'top '+ offset.y +' left ' + offset.x}"
    [ngClass]="{'defaultImage': imageService.getDefaultImageUrl() === imageUrl}"
>
  <button class="float-button" mat-icon-button (click)="editSeries()" *ngIf="canEdit">
    <mat-icon class="float-icon">build</mat-icon>
  </button>
  <header>
    <label class="series-name">{{userseries.series.title}}</label>
  </header>
  <div>
    <div class="seasons">{{userseries.season}}. évad, {{userseries.episode}}. rész</div>
    <div class="series-prodyear">{{userseries.series.prodYear}}</div>
    <div class="series-length">{{userseries.series.length}} perc</div>
    <div class="series-category">{{getCategories()}}</div>
  </div>
  <footer>
    <label class="age-limit" [ngStyle]="{'border-color': getLimitColor()}">{{userseries.series.ageLimit}}</label>
    <div class="status">
      <label>{{userseries.status.name}}</label>
    </div>
  </footer>
</div>
