// react-app/src/pages/handlers/misc-handler/MiscHandler.tsx
import { Button, TextField } from '@mui/material';
import { AxiosError } from 'axios';
import { useContext, useEffect, useState } from 'react';
import * as yup from 'yup';
import { DropdownBar } from '../../../components/items/drop-down-bar/DropdownBar';
import { SnackbarContext } from '../../../contexts/snackbarContext';
import { DropdownItem } from '../../../models/menu.model';
import { Category, Status } from '../../../models/series.model';
import { getCategoriesRequest, saveCategoryRequest, updateCategoryRequest } from '../../../utils/category-utils';
import { getStatusesRequest, saveStatusRequest, updateStatusRequest } from '../../../utils/status-utils';
import styles from './MiscHandler.module.css';

type StatusState = {
  id?: number;
  name: string;
}

type CategoryState = {
  id?: number;
  name: string;
}

type RefreshToken = {
  status: boolean;
  category: boolean;
}

type StatusErrorMessage = {
  [key in keyof StatusState]: string;
}

type CategoryErrorMessage = {
  [key in keyof CategoryState]: string;
}

export const MiscHandler = () => {
  const [statusState, setStatusState] = useState<StatusState>({ name: "" } as StatusState);
  const [categoryState, setCategoryState] = useState<CategoryState>({ name: "" } as CategoryState);
  const [statuses, setStatuses] = useState<Status[]>([]);
  const [categories, setCategories] = useState<Category[]>([]);
  const [statusesOptions, setStatusesOptions] = useState<DropdownItem[]>([]);
  const [categoriesOptions, setCategoriesOptions] = useState<DropdownItem[]>([]);
  const [statusErrorMessage, setStatusErrorMessage] = useState<StatusErrorMessage>({} as StatusErrorMessage);
  const [categoryErrorMessage, setCategoryErrorMessage] = useState<CategoryErrorMessage>({} as CategoryErrorMessage);
  const [refreshToken, setRefreshToken] = useState<RefreshToken>({ status: false, category: false });
  const { setMessage } = useContext(SnackbarContext);

  const onStatusChange = (e: any) => {
    e.preventDefault();
    setStatusState((pre) => ({
      ...pre,
      name: e.target.value,
    }))
  }
  const onCategoryChange = (e: any) => {
    e.preventDefault();
    setCategoryState((pre) => ({
      ...pre,
      name: e.target.value,
    }))
  }

  const selectStatus = (id: number) => {
    if(!id) {
      setStatusState({ name: "" });
      return;
    }

    const findStatus = statuses?.find((value) => value.id === id);
    if(!findStatus) {
      setMessage("Nem sikerült az állapot megnyitása!");
      return;
    }
    
    setStatusState(findStatus);
  }
  const selectCategory = (id: number) => {
    if(!id) {
      setCategoryState({ name: "" });
      return;
    }

    const findCategory = categories?.find((value) => value.id === id);
    if(!findCategory) {
      setMessage("Nem sikerült a kategória megnyitása!");
      return;
    }
    
    setCategoryState(findCategory);
  }

  const resetStatus = () => {
    setStatusState({ name: "" });
  }
  const resetCategory = () => {
    setCategoryState({ name: "" });
  }

  const refresh = (fieldName: keyof RefreshToken) => {
    setRefreshToken((pre) => ({
      ...pre,
      [fieldName]: !pre[fieldName]
    }));
  }

  const submitStatus = async (e: any) => {
    e.preventDefault();
    const errorMsg: StatusErrorMessage = {} as StatusErrorMessage;

    try {
      const result = await StatusSchema.validate(statusState, { abortEarly: false });
      if(result.id) {
        const response = await updateStatusRequest(result.id, result);
        setMessage(response, "success");
      } else {
        await saveStatusRequest(result);
        setMessage("Sikeres állapot felvétel!", "success");
      }
      resetStatus();
      refresh("status");
      setStatusErrorMessage(errorMsg);
    } catch(err) {
      if(err instanceof yup.ValidationError) {
        for(const error of err.inner) {
          errorMsg[(error.path as keyof StatusState)] = error.message;
        }
        setStatusErrorMessage(errorMsg);
      } else {
        setMessage((err as AxiosError<any>).response?.data.message);
      }
    }
  }
  const submitCategory = async (e: any) => {
    e.preventDefault();
    const errorMsg: CategoryErrorMessage = {} as CategoryErrorMessage;

    try {
      const result = await CategorySchema.validate(categoryState, { abortEarly: false });
      if(result.id) {
        const response = await updateCategoryRequest(result.id, result);
        setMessage(response, "success");
      } else {
        await saveCategoryRequest(result);
        setMessage("Sikeres kategória felvétel!", "success");
      }
      resetCategory();
      refresh("category");
      setCategoryErrorMessage(errorMsg);
    } catch(err) {
      if(err instanceof yup.ValidationError) {
        for(const error of err.inner) {
          errorMsg[(error.path as keyof CategoryState)] = error.message;
        }
        setCategoryErrorMessage(errorMsg);
      } else {
        setMessage((err as AxiosError<any>).response?.data.message);
      }
    }
  }

  useEffect(() => {
    getStatusesRequest()
      .then((statuses) => {
        setStatuses(statuses);
        setStatusesOptions([{ value: undefined, shownValue: "+" } ,...statuses.map((status) => ({ value: status.id, shownValue: status.name }) as DropdownItem)]);
      })
      .catch((err) => setMessage((err as AxiosError<any>).response?.data.message))
    
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [refreshToken.status]);

  useEffect(() => {
    getCategoriesRequest()
      .then((categories) => {
        setCategories(categories);
        setCategoriesOptions([{ value: undefined, shownValue: "+" } ,...categories.map((category) => ({ value: category.id, shownValue: category.name }) as DropdownItem)]);
      })
      .catch((err) => setMessage((err as AxiosError<any>).response?.data.message))
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [refreshToken.category]);

  return (
    <div className={styles["container"]}>
      <div className={styles["sub-container"]}>
        <div className={styles["title"]}>
          <label>Sorozat állapotok</label>
        </div>
        {statusState.id && <div className={styles["selected-id"]}>ID: {statusState.id}</div>}
        <form onSubmit={submitStatus}>
          <div className={styles["form-row"]}>
          <div className={styles["form-field"]}>
            <TextField className={styles["form-input"]} label="Állapot megnevezés" value={statusState.name} 
                onChange={onStatusChange} autoComplete="off" variant='standard'
                error={statusErrorMessage.name !== undefined} helperText={statusErrorMessage.name}
                />
          </div>
          <div className={styles["form-field"]}>
            <DropdownBar width='100%' className={styles["form-input"]} header="Állapotok" changeHeader={false} action={true} options={statusesOptions} setSelected={selectStatus}/>
          </div>
          </div>
          <Button className={styles["form-button"]} color="primary" type="submit" variant='contained' disabled={!StatusSchema.isValidSync(statusState)}
            >Mentés
            </Button>
        </form>
      </div>
      <div className={styles["sub-container"]}>
        <div className={styles["title"]}>
          <label>Kategóriák</label>
        </div>
        {categoryState.id && <div className={styles["selected-id"]}>ID: {categoryState.id}</div>}
        <form onSubmit={submitCategory}>
          <div className={styles["form-row"]}>
            <div className={styles["form-field"]}>
              <TextField className={styles["form-input"]} label="Kategória megnevezés" value={categoryState.name} 
                  onChange={onCategoryChange} autoComplete="off" variant='standard'
                  error={categoryErrorMessage.name !== undefined} helperText={categoryErrorMessage.name}
              />
            </div>
            <div className={styles["form-field"]}>
              <DropdownBar width='100%' className={styles["form-input"]} header="Kategóriák" changeHeader={false} action={true} options={categoriesOptions} setSelected={selectCategory}/>
            </div>
          </div>
          <Button className={styles["form-button"]} color="primary" type="submit" variant='contained' disabled={!CategorySchema.isValidSync(categoryState)}
            >Mentés
          </Button>
        </form>
      </div>
    </div>
  )
}

const StatusSchema = yup.object().shape({
  id: yup.number().min(1, "Hibás ID!"),
  name: yup.string().required("Kötelező megadni egy megnevezést!"),
})

const CategorySchema = yup.object().shape({
  id: yup.number().min(1, "Hibás ID!"),
  name: yup.string().required("Kötelező megadni egy megnevezést!"),
})

// angular/src/app/pages/handlers/misc-handler/misc-handler.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatSnackBar } from '@angular/material/snack-bar';
import { DropdownItem, ErrorMessage } from 'src/app/models/menu.model';
import { Category, Status } from 'src/app/models/series.model';
import { CategoryService } from 'src/app/services/category.service';
import { StatusService } from 'src/app/services/status.service';

@Component({
  selector: 'app-misc-handler',
  templateUrl: './misc-handler.component.html',
  styleUrls: ['./misc-handler.component.css']
})
export class MiscHandlerComponent implements OnInit {
  statusControl!: FormControl;
  categoryControl!: FormControl;
  statusOptions: DropdownItem[];
  categoryOptions: DropdownItem[];
  selectedCategory?: Category;
  selectedStatus?: Status;
  private categories: Category[];
  private statuses: Status[];
  constructor(private statusService: StatusService,
              private categoryService: CategoryService,
              private fb: FormBuilder,
              private snackbar: MatSnackBar) {
    this.categories = [];
    this.statuses = [];
    this.statusOptions = [];
    this.categoryOptions = [];
  }

  async ngOnInit() {
    this.categoryControl = this.fb.control("", [Validators.required]);
    this.statusControl = this.fb.control("", [Validators.required]);
    try {
      this.categories = await this.categoryService.getCategories();
      this.statuses = await this.statusService.getStatuses();
      this.setCategoryOptions();
      this.setStatusOptions();
    } catch(err) {
      this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
    }
  }

  setCategoryOptions = () => {
    if(!this.categories || this.categories.length < 1) {
      return;
    }

    this.categoryOptions = [{ value: 0, shownValue: "+" } as DropdownItem,
      ...this.categories.map((category) => ({ value: category.id, shownValue: category.name }) as DropdownItem)];
  }

  selectCategory = (id: number) => {
    if(id === 0) {
      this.selectedCategory = undefined;
      this.categoryControl.setValue("");
      return;
    }

    this.selectedCategory = this.categories.find((category) => category.id === id);
    if(!this.selectedCategory) {
      this.snackbar.open("Nem sikerült kiválasztani az állapotot!", 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
      return;
    }

    this.categoryControl.setValue(this.selectedCategory.name);
  }

  submitCategory = async () => {
    if(!this.categoryControl.valid) {
      return;
    }

    if(this.selectedCategory && this.selectedCategory.id) {
      try {
        const response = await this.categoryService.updateCategory(this.selectedCategory.id, { name: this.categoryControl.value });
        if(response) {
          this.snackbar.open(response, 'X', { duration: 3000, verticalPosition: 'bottom', panelClass: ['snackbar-success'] });
        }
      } catch(err) {
        this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
      }
    } else {
      try {
        const response = await this.categoryService.saveCategory({ name: this.categoryControl.value });
        if(response) {
          this.snackbar.open("Kategória mentés sikeres!", 'X', { duration: 3000, verticalPosition: 'bottom', panelClass: ['snackbar-success'] });
        }
      } catch(err) {
        this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
      }
    }
    this.selectedCategory = undefined;
    this.categoryControl.setValue("");
    this.categoryControl.markAsUntouched({ onlySelf: true });
    try {
      this.categories = await this.categoryService.getCategories();
      this.setCategoryOptions();
    } catch(err) {
      this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
    }
  }

  setStatusOptions = () => {
    if(!this.statuses || this.statuses.length < 1) {
      return;
    }

    this.statusOptions = [{ value: 0, shownValue: "+" } as DropdownItem,
    ...this.statuses.map((status) => ({ value: status.id, shownValue: status.name }) as DropdownItem)];
  }

  selectStatus = (id: number) => {
    if(id === 0) {
      this.selectedStatus = undefined;
      this.statusControl.setValue("");
      return;
    }

    this.selectedStatus = this.statuses.find((status) => status.id === id);
    if(!this.selectedStatus) {
      this.snackbar.open("Nem sikerült kiválasztani az állapotot!", 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
      return;
    }
    this.statusControl.setValue(this.selectedStatus.name);
  }

  submitStatus = async () => {
    if(!this.statusControl.valid) {
      return;
    }

    if(this.selectedStatus && this.selectedStatus.id) {
      try {
        const response = await this.statusService.updateStatus(this.selectedStatus.id, { name: this.statusControl.value });
        if(response) {
          this.snackbar.open(response, 'X', { duration: 3000, verticalPosition: 'bottom', panelClass: ['snackbar-success'] });
        }
      } catch(err) {
        this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
      }
    } else {
      try {
        const response = await this.statusService.saveStatus({ name: this.statusControl.value });
        if(response) {
          this.snackbar.open("Sorozat állapot mentés sikeres!", 'X', { duration: 3000, verticalPosition: 'bottom', panelClass: ['snackbar-success'] });
        }
      } catch(err) {
        this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
      }
    }

    this.selectedStatus = undefined;
    this.statusControl.setValue("");
    this.statusControl.markAsUntouched({ onlySelf: true });
    try {
      this.statuses = await this.statusService.getStatuses();
      this.setStatusOptions();
    } catch(err) {
      this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
    }
  }
}

<div class="container">
  <div class="sub-container">
    <div class="title">
      <label>Sorozat állapotok</label>
    </div>
    <div class="selected-id" *ngIf="selectedStatus">ID: {{selectedStatus.id}}</div>
    <form>
      <div class="form-row">
        <mat-form-field class="form-field">
          <mat-label>Állapot megnevezés</mat-label>
          <input matInput type="text" autocomplete="off" [formControl]="statusControl" required/>
        </mat-form-field>
        <app-drop-down-bar [header]="'Állapotok'" [options]="statusOptions" [changeHeader]="false"
          [action]="true" (selected)="selectStatus($event)"></app-drop-down-bar>
      </div>
      <button class="form-button" mat-raised-button color="primary" type="button"
        (click)="submitStatus()" [disabled]="!statusControl.valid">Mentés</button>
    </form>
  </div>
  <div class="sub-container">
    <div class="title">
      <label>Kategóriák</label>
    </div>
    <div class="selected-id" *ngIf="selectedCategory">ID: {{selectedCategory.id}}</div>
    <form>
      <div class="form-row">
        <mat-form-field class="form-field">
          <mat-label>Kategória megnevezés</mat-label>
          <input matInput type="text" autocomplete="off" [formControl]="categoryControl" required/>
        </mat-form-field>
        <app-drop-down-bar [header]="'Kategóriák'" [options]="categoryOptions" [changeHeader]="false"
          [action]="true" (selected)="selectCategory($event)"></app-drop-down-bar>
      </div>
      <button class="form-button" mat-raised-button color="primary" type="button"
        (click)="submitCategory()" [disabled]="!categoryControl.valid">Mentés</button>
    </form>
  </div>
</div>
