// react-app/src/pages/signup/Signup.tsx
import { Button, TextField } from '@mui/material';
import { useContext, useState } from 'react';
import { NewUser } from '../../models/user.model';
import * as yup from 'yup';
import styles from './Signup.module.css';
import { ErrorMessage } from '../../models/menu.model';
import { SnackbarContext } from '../../contexts/snackbarContext';
import { AuthContext } from '../../contexts/authContext';

type NewUserForm = {
  name?: string;
  birthdate?: string;
  username?: string;
  email?: string;
  password?: string;
  emailAgain?: string;
  passwordAgain?: string;
}

type NewUserErrorMessage = {
  [key in keyof NewUserForm]: string;
}

const initState: NewUserForm = {
  name: "",
  birthdate: "",
  username: "",
  email: "",
  emailAgain: "",
  password: "",
  passwordAgain: "",
}

export const Signup = () => {
  const [state, setState] = useState<NewUserForm>(initState);
  const [showPassword, setShowPassword] = useState(false);
  const [errorMessage, setErrorMessage] = useState<NewUserErrorMessage>({} as NewUserErrorMessage);
  const { setMessage } = useContext(SnackbarContext);
  const { signup } = useContext(AuthContext);

  const submit = async (e: any) => {
    e.preventDefault();
    const errorMsg: NewUserErrorMessage = {} as NewUserErrorMessage;
    try { 
      const result = await SignupSchema.validate(state, { abortEarly: false });

      delete result.emailAgain;
      delete result.passwordAgain;
      const newUser: NewUser = {
        ...result,
        birthdate: result.birthdate.toISOString().split("T")[0]
      };

      const response = await signup(newUser);

      resetState();
      setMessage(response.message, "success");
      setErrorMessage(errorMsg)
    } catch(err) {
      if(err instanceof yup.ValidationError) {
        for(const error of err.inner) {
          errorMsg[(error.path as keyof NewUserForm)] = error.message;
        }
        setErrorMessage(errorMsg)
      } else {
        setMessage((err as ErrorMessage).message);
      }
    }
  }

  const toggle = () => {
    setShowPassword((pre) => !pre);
  }

  const handleChange = (e: any, fieldName: string) => {
    setState((pre) => ({
      ...pre,
      [fieldName]: e.target.value
    }))
  }

  const resetState = () => {
    setState(initState);
  }

  return (
    <div id={styles["signup-container"]}>
      <div>
        <span className={styles["title"]}>Regisztráció</span>
      </div>
      <form onSubmit={submit} id={styles["signup-form"]}>
        <span className={styles["sub-title"]}>Személyes adatok</span>
        <div className={styles["form-row"]}>
          <div className={styles['form-field']}>
            <TextField className={styles['form-field-input']} InputLabelProps={{ style:{transformOrigin: "50%" }}} label="Név" 
                error={errorMessage.name !== undefined} helperText={errorMessage.name}
                onChange={(event) => handleChange(event, "name")} variant="standard" value={state.name}/>
          </div>
          <div className={styles['form-field']}>
            <TextField type={'date'} className={styles['form-field-input']} InputLabelProps={{ 
                style:{transformOrigin: "50%" }, shrink: true}} label="Születési dátum"
                error={errorMessage.birthdate !== undefined} helperText={errorMessage.birthdate}
                onChange={(event) => handleChange(event, "birthdate")} variant="standard" value={state.birthdate}/>
          </div>
        </div>
        <span className={styles["sub-title"]}>Fiók adatok</span>
        <div className={styles["left-aligned-row"]}>
          <div className={styles['form-field']}>
            <TextField className={styles['form-field-input']} label="Felhasználónév" InputLabelProps={{ style:{transformOrigin: "50%" }}}
                error={errorMessage.username !== undefined} helperText={errorMessage.username}
                onChange={(event) => handleChange(event, "username")} variant="standard" value={state.username}/>
          </div>
        </div>
        <div className={styles["form-row"]}>
          <div className={styles['form-field']}>
            <TextField className={styles['form-field-input']} label="Email" InputLabelProps={{ style:{transformOrigin: "50%" }}}
                error={errorMessage.email !== undefined} helperText={errorMessage.email}
                onChange={(event) => handleChange(event, "email")} variant="standard" value={state.email}/>
          </div>
          <div className={styles['form-field']}>
            <TextField className={styles['form-field-input']} label="Email újra" InputLabelProps={{ style:{transformOrigin: "50%" }}}
                error={errorMessage.emailAgain !== undefined} helperText={errorMessage.emailAgain}
                onChange={(event) => handleChange(event, "emailAgain")} variant="standard" value={state.emailAgain}/>
          </div>
        </div>
        <div className={styles["form-row"]}>
        <div className={styles['form-field']}>
            <TextField type={showPassword ? 'text' : 'password'} className={styles['form-field-input']} label="Jelszó" 
                error={errorMessage.password !== undefined} helperText={errorMessage.password}
                InputLabelProps={{ style:{transformOrigin: "50%" }}} onChange={(event) => handleChange(event, "password")} variant="standard" value={state.password}/>
            
          </div>
          <div className={styles['form-field']}>
            <TextField type={showPassword ? 'text' : 'password'} className={styles['form-field-input']} label="Jelszó újra"
                error={errorMessage.passwordAgain !== undefined} helperText={errorMessage.passwordAgain}
                InputLabelProps={{ style:{transformOrigin: "50%" }}} onChange={(event) => handleChange(event, "passwordAgain")} variant="standard" value={state.passwordAgain}/>
          </div>
        </div>
        <div className={styles["show-password"]} onClick={toggle}>
          <input id={styles["show-password-button"]} type="checkbox" checked={showPassword} onChange={() => {}}/>
          <label id={styles["show-password-text"]}>Mutasd a jelszót!</label>
        </div>
        <div id={styles["form-button"]}>
          <Button type="submit" disabled={!SignupSchema.isValidSync(state)} variant='contained'>Regisztráció</Button>
        </div>
      </form>
    </div>
  )
}

const SignupSchema = yup.object().shape({
  name: yup.string().required("Név megadása kötelező!"),
  birthdate: yup.date().required("Születési dátum megadása kötelező!"),
  username: yup.string().required("Felhasználónév megadása kötelező!"),
  email: yup.string().email("Valid emailnek kell lennie!").required("Email megadása kötelező!"),
  emailAgain: yup.string().email("Valid emailnek kell lennie!").test("Email egyezés", "Emailek nem egyeznek", function(value) {return !this.parent?.email || value === this.parent?.email}),
  password: yup.string().required("Jelszó megadása kötelező!"),
  passwordAgain: yup.string().test("Jelszó egyezés", "Jelszók nem egyeznek", function(value) {return !this.parent?.password || value === this.parent?.password})
});

// angular/src/app/pages/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MatSnackBar } from '@angular/material/snack-bar';
import { Router } from '@angular/router';
import { NewUser } from 'src/app/models/user.model';
import { AuthService } from 'src/app/services/auth.service';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css']
})
export class SignupComponent implements OnInit {
  showPassword: boolean;
  formGroup!: FormGroup;
  constructor(private fb: FormBuilder,
              private authService: AuthService,
              private router: Router,
              private snackbar: MatSnackBar) {
    this.showPassword = false;
  }

  ngOnInit(): void {
    this.formGroup = this.fb.group({
      name: ['', [Validators.required]],
      birthdate: [null, [Validators.required]],
      username: ['', [Validators.required]],
      email: ['', [Validators.required, Validators.email]],
      emailAgain: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required]],
      passwordAgain: ['', [Validators.required]],
    });

    this.formGroup.get("emailAgain")?.addValidators((email) => {
      return this.formGroup.get("email")?.value === email.value
        ? null
        : { notSame: true };
    });
    this.formGroup.get("passwordAgain")?.addValidators((password) => {
      return this.formGroup.get("password")?.value === password.value
        ? null
        : { notSame: true };
    });
  }

  toggle = () => {
    this.showPassword = !this.showPassword;
  }

  submit = async () => {
    if(!this.formGroup.valid) {
      return;
    }

    const newUser: NewUser = {
      name: this.formGroup.value.name,
      birthdate: this.formGroup.value.birthdate,
      username: this.formGroup.value.username,
      email: this.formGroup.value.email,
      password: this.formGroup.value.password
    };

    try {
      const response = await this.authService.signup(newUser);
      this.snackbar.open(response.message, "X", { verticalPosition: "bottom", duration: 3000, panelClass: ["snackbar-success"] });
      this.router.navigate(['/login'], { replaceUrl: true });
    } catch(err) {
      this.snackbar.open((err as { message: string }).message, "X", { verticalPosition: "bottom", duration: 3000, panelClass: ["snackbar-error"] })
    }
  }

  getError = (controllName: string) => {
    if(this.formGroup.get(controllName)?.getError("required")) {
      return "Kötelező mező!"
    }
    if(this.formGroup.get(controllName)?.getError("notSame")) {
      return "Nem egyezik meg a megismételt mező a másikkal!"
    }

    return "Hibásan kitöltött mező!"
  }
}

<div id="signup-container">
  <div>
    <span class="title">Regisztráció</span>
  </div>
  <form [formGroup]="formGroup" id="signup-form" (submit)="submit()">
    <span class="sub-title">Személyes adatok</span>
    <div class="form-row">
      <mat-form-field class="form-field">
        <mat-placeholder>Név</mat-placeholder>
        <mat-error>Kötelező mező!</mat-error>
        <input matInput type="text" formControlName="name"/>
      </mat-form-field>
      <mat-form-field class="form-field">
        <mat-placeholder>Születési dátum</mat-placeholder>
        <mat-error>Kötelező mező!</mat-error>
        <input matInput type="date" formControlName="birthdate"/>
      </mat-form-field>
    </div>
    <span class="sub-title">Fiók adatok</span>
    <div class="left-aligned-row">
      <mat-form-field class="form-field">
        <mat-placeholder>Felhasználónév</mat-placeholder>
        <mat-error>Kötelező mező!</mat-error>
        <input matInput type="text" formControlName="username"/>
      </mat-form-field>
    </div>
    <div class="form-row">
      <mat-form-field class="form-field">
        <mat-placeholder>Email</mat-placeholder>
        <mat-error>Kötelező mező!</mat-error>
        <input matInput type="email" formControlName="email"/>
      </mat-form-field>
      <mat-form-field class="form-field">
        <mat-placeholder>Email újra</mat-placeholder>
        <mat-error>{{getError("emailAgain")}}</mat-error>
        <input matInput type="email" formControlName="emailAgain"/>
      </mat-form-field>
    </div>
    <div class="form-row">
      <mat-form-field class="form-field">
        <mat-placeholder>Jelszó</mat-placeholder>
        <mat-error>Kötelező mező!</mat-error>
        <input matInput [type]="showPassword ? 'text' : 'password'" formControlName="password"/>
      </mat-form-field>
      <mat-form-field class="form-field">
        <mat-placeholder>Jelszó újra</mat-placeholder>
        <mat-error>{{getError("passwordAgain")}}</mat-error>
        <input matInput [type]="showPassword ? 'text' : 'password'" formControlName="passwordAgain"/>
      </mat-form-field>
    </div>
    <div class="show-password" (click)="toggle()">
      <input id="show-password-button" type="checkbox" [checked]="showPassword"/>
      <label id="show-password-text">Mutasd a jelszót!</label>
    </div>
    <div id="form-button">
      <button mat-raised-button color="accent" [disabled]="!formGroup.valid">Regisztráció</button>
    </div>
  </form>
</div>
