// angular/src/app/components/sidebar/sidebar.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { SidebarItem } from 'src/app/models/menu.model';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css']
})
export class SidebarComponent implements OnInit {
  closed: boolean;
  @Input() items: SidebarItem[];
  constructor() {
    this.closed = true;
    this.items = [];
  }

  ngOnInit(): void {
  }

  toggle = () => {
    this.closed = !this.closed;
  }
}

<div>
  <button id="sidebar-icon-button" (click)="toggle()" mat-button>
    <mat-icon id="sidebar-icon" title="Oldalsáv">menu</mat-icon>
  </button>
  <div id="sidebar-body" [hidden]="closed">
    <div class="sidebar-item" *ngFor="let item of items">
      <a class="sidebar-item-text" [routerLink]="item.link" (click)="toggle()">{{item.name}}</a>
      <hr class="sidebar-spacer" />
    </div>
  </div>
</div>

// react-app/src/components/sidebar/Sidebar.tsx
import { Link } from 'react-router-dom';
import styles from './Sidebar.module.css';
import { IconButton, Icon } from '@mui/material';
import { useContext, useState } from 'react';
import { AuthContext } from '../../contexts/authContext';

export function Sidebar() {
  const [open, setOpen] = useState(false);
  const { sidebarItems } = useContext(AuthContext);

  const toggle = () => {
    setOpen((preValue) => !preValue);
  }

  return (
    <div id={styles["sidebar"]} hidden={!sidebarItems}>
      <IconButton id={styles["sidebar-icon-button"]} title="Oldalsáv" onClick={() => toggle()}>
        <Icon id={styles["sidebar-icon"]}>menu</Icon>
      </IconButton>
      <div className={`${styles["sidebar-body"]} ${open ? styles["expanded"] : ''}`}>
        {sidebarItems && sidebarItems.map(item => (
          <div className={styles["sidebar-item"]}>
          <Link to={item.link} className={styles["sidebar-item-text"]} onClick={() => toggle()}>{item.name}</Link>
          <hr className={styles["sidebar-spacer"]}/>
        </div>
        ))}
        
      </div>
    </div>
  )
}
