// react-app/src/components/items/newsfeed-item/NewsfeedItem.tsx
import { Icon, IconButton } from '@mui/material';
import { FC, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Newsfeed } from '../../../models/newsfeed.model';
import { User } from '../../../models/user.model';
import { hasRight } from '../../../utils/auth-utils';
import styles from './NewsfeedItem.module.css';

type NewsfeedItemProps = {
  newsfeed: Newsfeed,
  user?: User,
}

type NewsfeedItemState = {
  canAccess: boolean;
}

export const NewsfeedItem: FC<NewsfeedItemProps> = ({ newsfeed, user }) => {
  const [state, setState] = useState<NewsfeedItemState>({ canAccess: false });
  const navigate = useNavigate();

  const editNewsfeed = () => {
    navigate(`/admin/newsfeed/${newsfeed.id}`);
  }

  useEffect(() => {
    const tempState: NewsfeedItemState = {} as NewsfeedItemState;
    tempState.canAccess = hasRight(["siteManager", "admin"], user);
    setState(tempState);
  }, [user]);

  return (
    <div className={styles["newsfeed-item"]}>
      <div className={styles["edit-button"]}>
        {state.canAccess &&
        <IconButton onClick={editNewsfeed}>
          <Icon fontSize='small' className={styles["edit-icon"]}>build</Icon>
        </IconButton>}
      </div>
      <div className={styles["newsfeed-header"]}>
        <div className={styles["header-title"]}>
          <label className={styles["title"]}>{newsfeed.title}</label>
          <label className={styles["modification"]}>{newsfeed.modification.split("T")[0]}</label>
        </div>
        <div className={styles["header-subtitle"]}>
          <label className={styles["series-name"]}>{newsfeed.series.title}</label>
        </div>
      </div>
      <div className={styles["newsfeed-body"]}>
        <label>
          {newsfeed.description}
        </label>
      </div>
    </div>
  )
}

// angular/src/app/components/items/newsfeed-item/newsfeed-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Newsfeed } from 'src/app/models/newsfeed.model';
import { AuthService } from 'src/app/services/auth.service';

@Component({
  selector: 'app-newsfeed-item',
  templateUrl: './newsfeed-item.component.html',
  styleUrls: ['./newsfeed-item.component.css']
})
export class NewsfeedItemComponent implements OnInit {
  @Input() newsfeed!: Newsfeed;
  canAccess: boolean;
  constructor(private router: Router,
              private authService: AuthService) {
    this.canAccess = false;
  }

  ngOnInit(): void {
    this.canAccess = this.authService.hasRight(["siteManager", "admin"]);
  }

  editNewsfeed = () => {
    this.router.navigateByUrl(`/admin/newsfeed/${this.newsfeed.id}`);
  }
}

<div class="newsfeed-item">
  <button class="edit-button" mat-icon-button (click)="editNewsfeed()" *ngIf="canAccess">
    <mat-icon class="edit-icon">build</mat-icon>
  </button>
  <div class="newsfeed-header">
    <div class="header-title">
      <label class="title">{{newsfeed.title}}</label>
      <label class="modification">{{newsfeed.modification.split("T")[0]}}</label>
    </div>
    <div class="header-subtitle">
      <label class="series-name">{{newsfeed.series.title}}</label>
    </div>
  </div>
  <div class="newsfeed-body">
    <label>
      {{newsfeed.description}}
    </label>
  </div>
</div>
