// react-app/src/pages/handlers/userseries-handler/UserseriesHandler.tsx
import { Button } from '@mui/material';
import { AxiosError } from 'axios';
import { useCallback, useContext, useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Confirmation } from '../../../components/items/confirmation/Confirmation';
import { DropdownBar } from '../../../components/items/drop-down-bar/DropdownBar';
import { SearchBar } from '../../../components/items/search-bar/SearchBar';
import { SnackbarContext } from '../../../contexts/snackbarContext';
import { AutoCompleteItem, DropdownItem } from '../../../models/menu.model';
import { Status, UserSeries } from '../../../models/series.model';
import { getStatusesRequest } from '../../../utils/status-utils';
import { deleteUserSeriesRequest, getUserSeriesesRequest, getUserSeriesRequest, updateUserSeriesRequest } from '../../../utils/userseries-utils';
import styles from './UserseriesHandler.module.css';

export const UserseriesHandler = () => {
  const [searchValue, setSearchValue] = useState("");
  const [autocompleteOptions, setAutocompleteOptions] = useState<AutoCompleteItem[]>([]);
  const [seriesId, setSeriesId] = useState<number | undefined>(undefined);
  const [userseries, setUserseries] = useState<UserSeries | undefined>(undefined);
  const [statuses, setStatuses] = useState<Status[]>([]);
  const [openConfirmation, setOpenConfirmation] = useState(false);
  const navigate = useNavigate();
  const { id } = useParams();
  const { setMessage } = useContext(SnackbarContext);

  const submit = async (e: any) => {
    e.preventDefault();

    try {
      const response = await updateUserSeriesRequest(seriesId, userseries);
      if(response) {
        setMessage(response, "success");
        resetValues();
      }
    } catch(err) {
      if((err as AxiosError<any>).response.status === 401) {
        navigate("/logout");
      }
      setMessage((err as AxiosError<any>).response.data.message)
    }
  } 
  const remove = async () => {
    try {
      const response = await deleteUserSeriesRequest(seriesId);
      if(response) {
        setMessage(response, "success");
        navigate("/user/series");
      }
    } catch(err) {
      if((err as AxiosError<any>).response.status === 401) {
        navigate("/logout");
      }
      setMessage((err as AxiosError<any>).response.data.message)
    }
  }

  const setSearchValueWrapper = (searchValue: string) => {
    setSearchValue(searchValue);
  }
  const setAutocompleteValue = (seriesId: number) => {
    navigate(`/user/handle/series/${seriesId}`)
  }
  const setStatus = (statusId: number) => {
    const status = statuses.find((st) => st.id === statusId);
    if(status) {
      setUserseries((pre) => ({
        ...pre,
        status: status
      }));
    }
  }
  const closeConfirmation = () => {
    setOpenConfirmation(false);
  }
  const setSeason = (season: number) => {
    setUserseries((pre) => ({
      ...pre,
      season,
      episode: 1,
    }));
  }
  const setEpisode = (episode: number) => {
    setUserseries((pre) => ({
      ...pre,
      episode
    }));
  }

  const fetchUserseriesData = useCallback(async () => {
    try {
      const response = await getUserSeriesRequest(seriesId);
      if(response) {
        setUserseries(response);
      }
    } catch(err) {
      if((err as AxiosError<any>).response.status === 401) {
        navigate("/logout");
      }
      setMessage((err as AxiosError<any>).response.data.message)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [seriesId]);
  const fetchUserseriesDataAndMakeOptions = useCallback(async () => {
    try {
      const response = await getUserSeriesesRequest(1, 10, -1, searchValue);
      if(response) {
        setAutocompleteOptions(response.serieses.map((userseries) => ({ value: userseries.series.id, label: `${userseries.series.id}, ${userseries.series.title} | ${userseries.series.prodYear}`}) as AutoCompleteItem));
      }
    } catch(err) {
      if((err as AxiosError<any>).response.status === 401) {
        navigate("/logout");
      }
      setMessage((err as AxiosError<any>).response.data.message)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [searchValue]);
  const fetchStatusesData = useCallback(async () => {
    try {
      const response = await getStatusesRequest();
      if(response) {
        setStatuses(response);
      }
    } catch(err) {
      if((err as AxiosError<any>).response.status === 401) {
        navigate("/logout");
      }
      setMessage((err as AxiosError<any>).response.data.message)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const resetValues = () => {
    setSearchValue("");
    setAutocompleteOptions([]);
    fetchUserseriesData();
  }
  const getCategories = useCallback((): string => {
    if(userseries) {
      return userseries.series.categories.map((category) => category.name).join(", ") as string;
    }
    return "";
  }, [userseries]);
  const getStatusOptions = useCallback(() => {
    return statuses.map((status) => ({ value: status.id, shownValue: status.name, highlight: status.id === userseries.status.id }) as DropdownItem);
  }, [statuses, userseries]);
  const getSeasonOptions = () => {
    return userseries.series.seasons.map(season => ({ value: season.season, shownValue: season.season+'. Évad', highlight: season.season === userseries.season}) as DropdownItem);
  };
  const getEpisodeOptions = useCallback(() => {
    const episodeOptions: DropdownItem[] = [];
    const season = userseries.series.seasons.find((season) => season.season === userseries.season);

    if(season) {
      for(let i = 1; i <= season.episode; i++) {
        episodeOptions.push({ value: i, shownValue: i+'. Epizód', highlight: i === userseries.episode});
      }
    }
    return episodeOptions;
  }, [userseries]);

  useEffect(() => {
    
  }, [userseries]);
  useEffect(() => {
    fetchUserseriesDataAndMakeOptions()
  }, [searchValue, fetchUserseriesDataAndMakeOptions]);
  useEffect(() => {
    if(seriesId) {
      fetchUserseriesData();
    }
  }, [seriesId, fetchUserseriesData]);
  useEffect(() => {
    if(!isNaN(Number(id))) {
      setSeriesId(Number(id));
    }
  }, [id]);
  useEffect(() => {
    fetchStatusesData();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div>
      <Confirmation open={openConfirmation} handleClose={closeConfirmation} question="Biztos hogy eltávolítod?" onAccept={remove}/>
      <div className={styles["container"]}>
        <div className={styles["search"]}>
          <SearchBar options={autocompleteOptions} setSearchValue={setSearchValueWrapper} setAutocompleteValue={setAutocompleteValue}/>
        </div>
        {userseries &&
        <div className={styles["form-container"]}>
          <div className={styles["form-header"]}>
            <div className={styles["title"]}>
              <label>Sorozat módosítás</label>
            </div>
            <div className={styles["id"]}>
              <label>ID: {userseries.series.id}</label>
            </div>
          </div>
          <div className={styles["form-details"]}>
            <div className={styles["details-row"]}>
              <div>Cím: {userseries.series.title}</div>
              <div>Kategória: {getCategories()}</div>
            </div>
            <div className={styles["details-row"]}>
              <div>Kiadási év: {userseries.series.prodYear}</div>
              <div>Hossz: {userseries.series.length} perc</div>
            </div>
          </div>
          <div>
            <div className={styles["form-drop-bars"]}>
              <DropdownBar options={getSeasonOptions()} header={userseries.season+'. Évad'} action={true} setSelected={setSeason}/>
              <DropdownBar options={getEpisodeOptions()} header={userseries.episode+'. Epizód'} action={true} setSelected={setEpisode}/>
              <DropdownBar options={getStatusOptions()} header={userseries.status.name} action={true} setSelected={setStatus}/>
            </div>
            <div  className={styles["button-container"]}>
              <Button className={styles["form-button"]} variant="contained" onClick={submit}>Mentés</Button>
              <Button className={styles["form-button"]} variant="contained" onClick={() => setOpenConfirmation(true)} color="error">Törlés</Button>
            </div>
          </div>
        </div>}
      </div>
    </div>
  )
}

// angular/src/app/pages/handlers/userseries-handler/userseries-handler.component.ts
import { Component, OnInit } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { MatSnackBar } from '@angular/material/snack-bar';
import { ActivatedRoute, Router } from '@angular/router';
import { ConfirmationComponent } from 'src/app/components/items/confirmation/confirmation.component';
import { DropdownItem, ErrorMessage } from 'src/app/models/menu.model';
import { Season, Status, UserSeries } from 'src/app/models/series.model';
import { StatusService } from 'src/app/services/status.service';
import { UserSeriesService } from 'src/app/services/user-series.service';

@Component({
  selector: 'app-userseries-handler',
  templateUrl: './userseries-handler.component.html',
  styleUrls: ['./userseries-handler.component.css']
})
export class UserseriesHandlerComponent implements OnInit {
  seriesId?: number;
  seriesOptions: DropdownItem[];
  statusOptions: DropdownItem[];
  seasonOptions: DropdownItem[];
  episodeOptions: DropdownItem[];
  selectedSeason?: Season;
  selectedEpisode?: number;
  selectedStatus?: Status;
  selectedUserSeries?: UserSeries;
  private statuses: Status[];
  constructor(private userSeriesService: UserSeriesService,
              private statusService: StatusService,
              private snackbar: MatSnackBar,
              private dialog: MatDialog,
              private route: ActivatedRoute,
              private router: Router) {
    this.seriesOptions = [];
    this.statusOptions = [];
    this.seasonOptions = [];
    this.episodeOptions = [];
    this.statuses = [];
  }

  async ngOnInit() {
    const tempId = this.route.snapshot.paramMap.get("id");
    if(tempId) {
      this.seriesId = Number(tempId);
      try {
        this.statuses = await this.statusService.getStatuses();
        this.selectedUserSeries = await this.userSeriesService.getUserSeries(this.seriesId);
        if(!this.selectedUserSeries) {
          this.snackbar.open("Váratlan hiba, töltsd újra a módosítandó sorozatot!", 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
          this.router.navigateByUrl("user/handle/series", { replaceUrl: true });
          return;
        }

        this.setStatusOption(this.selectedUserSeries.status.id as number);
        const season: Season = this.selectedUserSeries.series.seasons.find((season) => season.season === this.selectedUserSeries?.season) as Season;
        if(season) {
          this.setSeasonOption(season)
        }
        this.setEpisodeOption(this.selectedUserSeries.episode);
      } catch(err) {
        this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
        // this.resetSelectedDatas()
      }
    }
  }

  submit = async () => {
    let updateUserSeries: UserSeries = {} as UserSeries;
    if(this.selectedSeason && this.selectedSeason.season !== this.selectedUserSeries?.season) {
      updateUserSeries.season = this.selectedSeason?.season;
    }

    if(this.selectedEpisode && this.selectedEpisode !== this.selectedUserSeries?.episode) {
      updateUserSeries.episode = this.selectedEpisode;
    }

    if(this.selectedStatus && this.selectedStatus.id !== this.selectedUserSeries?.status.id) {
      updateUserSeries.status = { id: this.selectedStatus.id } as Status;
    }

    if(!this.changeHappened() || !this.seriesId) {
      this.snackbar.open("Eddig nem történt adat változtatás!", 'X', { duration: 4000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
      return;
    }
    try {
      const result = await this.userSeriesService.updateUserSeries(this.seriesId, updateUserSeries);
      if(result) {
        this.snackbar.open(result, 'X', { duration: 3000, verticalPosition: 'bottom', panelClass: ['snackbar-success'] });
        this.router.navigateByUrl("/user/series");
        return;
      }
    } catch(err) {
      this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
    }
  }

  remove = () => {
      const dialogRef = this.dialog.open(ConfirmationComponent, { data: { question: "Biztos szeretnéd törölni a sorozatot?" }});

      dialogRef.afterClosed().subscribe(async (response) => {
        if(response) {
          if(!this.seriesId) {
            this.snackbar.open("Váratlan hiba merült fel, töltsd újra a törlendő sorozatot!", 'X', { duration: 4000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
            return;
          }
          try {
            const res = await this.userSeriesService.deleteUserSeries(this.seriesId);
            if(res) {
              this.snackbar.open(res, 'X', { duration: 3000, verticalPosition: 'bottom', panelClass: ['snackbar-success'] });
              this.router.navigateByUrl("/user/series");
              return;
            }
          } catch(err) {
            this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
          }
        }
      });
  }

  changeHappened = (): boolean | undefined => {
    return (this.selectedSeason && this.selectedUserSeries && this.selectedSeason.season !== this.selectedUserSeries?.season) ||
      (this.selectedEpisode && this.selectedUserSeries && this.selectedEpisode !== this.selectedUserSeries?.episode) ||
      (this.selectedStatus && this.selectedUserSeries && this.selectedStatus.id !== this.selectedUserSeries?.status.id);
  }

  captureValue = async (value: string) => {
    try {
      const response = await this.userSeriesService.getUserSerieses(1, 10, undefined, value);
      this.seriesOptions = response.serieses
      ? response.serieses
        .map((userseries) => ({
          value: userseries.series.id,
          shownValue: `${userseries.series.title}, ${userseries.series.prodYear}`
        }) as DropdownItem)
      : [];
    } catch(err) {
      this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
    }
  }

  autocompleteValue = async (value: any) => {
    this.seriesId = value;
    if(this.seriesId) {
      this.selectedUserSeries = await this.userSeriesService.getUserSeries(this.seriesId);
      this.router.navigateByUrl(`user/handle/series/${this.seriesId}`, { replaceUrl: true });
      this.resetSelectedDatas();
      this.getSeasonOptions();
      this.getEpisodeOptions();
      this.getStatusOptions();
    }
  }

  seriesDoesntHaveSeasons = () => {
    return !this.selectedUserSeries?.series.seasons || this.selectedUserSeries?.series.seasons.length < 1;
  }

  getSeasonOptions = () => {
    if(this.selectedUserSeries) {
      if(this.seriesDoesntHaveSeasons()) {
        this.seasonOptions = [];
        return;
      }

      this.seasonOptions = this.selectedUserSeries.series.seasons?.map((season) => ({ value: season, shownValue: `${season.season}. Évad`, highlight: season.season === this.selectedSeason?.season }) as DropdownItem);
      return;
    }

    this.seasonOptions = [];
  }

  setSeasonOption = (season: Season) => {
    this.selectedSeason = season;
    this.setEpisodeOption(1);
    this.getSeasonOptions();
  }

  getEpisodeOptions = () => {
    if(this.selectedUserSeries && this.selectedSeason && !this.seriesDoesntHaveSeasons()) {
      const options: DropdownItem[] = [];
      for (let index = 1; index <= this.selectedSeason.episode; index++) {
        options.push({ value: index, shownValue: `${index}. Epizód`, highlight: index === this.selectedEpisode });
      }
      this.episodeOptions =  options;
      return;
    }

    this.episodeOptions = [];
  }

  setEpisodeOption = (episode: number) => {
    this.selectedEpisode = episode;
    this.getEpisodeOptions();
  }

  getStatusOptions = async () => {
    this.statusOptions = this.statuses.map((status) => ({ value: status.id, shownValue: status.name, highlight: status.id === this.selectedStatus?.id }));
  }

  setStatusOption = (statusId: number) => {
    this.selectedStatus = this.statuses.find(status => status.id === statusId);
    this.getStatusOptions();
  }

  getCategories = (): string => {
    if(this.selectedUserSeries) {
      return this.selectedUserSeries.series.categories.map((category) => category.name).join(", ") as string;
    }
    return "";
  }

  resetSelectedDatas = () => {
    if(this.selectedUserSeries && this.selectedUserSeries.series.seasons && this.selectedUserSeries.series.seasons.length > 0) {
      this.selectedSeason = this.selectedUserSeries.series.seasons.find((season) => season.season === this.selectedUserSeries?.season);
      this.selectedEpisode = this.selectedUserSeries?.episode;
      this.selectedStatus = this.selectedUserSeries?.status;
    }
  }
}

<div>
  <div class="container">
    <div class="search">
      <app-search-bar [options]="seriesOptions" (searchValue)="captureValue($event)" (selectedValue)="autocompleteValue($event)"></app-search-bar>
    </div>
    <div class="form-container" *ngIf="selectedUserSeries">
      <div class="form-header">
        <div class="title">
          <label>Sorozat módosítás</label>
        </div>
        <div class="id">
          <label>ID: {{selectedUserSeries.series.id}}</label>
        </div>
      </div>
      <div class="form-details">
        <div class="details-row">
          <div>Cím: {{selectedUserSeries.series.title}}</div>
          <div>Kategória: {{getCategories()}}</div>
        </div>
        <div class="details-row">
          <div>Kiadási év: {{selectedUserSeries.series.prodYear}}</div>
          <div>Hossz: {{selectedUserSeries.series.length}} perc</div>
        </div>
      </div>
      <div>
        <div class="form-drop-bars">
          <app-drop-down-bar [header]="selectedSeason?.season + '. Évad'" [action]="true"
            [options]="seasonOptions" (selected)="setSeasonOption($event)"></app-drop-down-bar>
          <app-drop-down-bar [header]="selectedEpisode + '. Epizód'" [action]="true"
            [options]="episodeOptions" (selected)="setEpisodeOption($event)"></app-drop-down-bar>
          <app-drop-down-bar [header]="selectedStatus?.name+''" [action]="true"
            [options]="statusOptions" (selected)="setStatusOption($event)"></app-drop-down-bar>
        </div>
        <button class="form-button" mat-raised-button (click)="submit()">Mentés</button>
        <button class="form-button" mat-raised-button (click)="remove()" color="warn">Törlés</button>
      </div>
    </div>
  </div>
</div>
