// angular/src/app/pages/handlers/user-handler/user-handler.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';
import { MatSnackBar } from '@angular/material/snack-bar';
import { ActivatedRoute, Router } from '@angular/router';
import { ConfirmationComponent } from 'src/app/components/items/confirmation/confirmation.component';
import { DropdownItem, ErrorMessage } from 'src/app/models/menu.model';
import { NewUser, Role, User } from 'src/app/models/user.model';
import { UserService } from 'src/app/services/user.service';

@Component({
  selector: 'app-user-handler',
  templateUrl: './user-handler.component.html',
  styleUrls: ['./user-handler.component.css']
})
export class UserHandlerComponent implements OnInit {
  lockPassword: boolean;
  activated: boolean;
  formGroup!: FormGroup;
  filter: string;
  userId?: number;
  selectedUser?: User;
  private roles: Role[];
  constructor(private router: Router,
              private route: ActivatedRoute,
              private snackbar: MatSnackBar,
              private fb: FormBuilder,
              private userService: UserService,
              private dialog: MatDialog) {
    this.filter = "";
    this.roles = [];
    this.lockPassword = true;
    this.activated = true;
  }

  async ngOnInit() {
    this.formGroup = this.fb.group({
      name: ['', [Validators.required]],
      birthdate: [undefined, [Validators.required]],
      email: ['', [Validators.required, Validators.email]],
      role: [{id: 0, name: 'unknown'}],
      password: [{value: '', disabled: true}]
    });

    this.roles = await this.userService.getRoles();
    const tempId = this.route.snapshot.paramMap.get("id");
    if(tempId) {
      this.setValues(Number(tempId));
    }
  }

  submit = async () => {
    if(!this.activated) {
      const dialogRef = this.dialog.open(ConfirmationComponent, { data: {question: "Biztos szeretnéd deaktiválni?"} });

      dialogRef.afterClosed().subscribe(async (response) => {
        if(response) {
          if(!this.userId) {
            this.snackbar.open("Nem sikerült deaktiválni, töltsd újra a deaktiválandó felhasználót!", 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
            return;
          }

          try {
            const res = await this.userService.deleteUser(this.userId);
            if(res) {
              this.snackbar.open(res, 'X', { duration: 3000, verticalPosition: 'bottom', panelClass: ['snackbar-success'] });
              this.router.navigateByUrl(`/admin/user`, { replaceUrl: true });
            }
          } catch(err) {
            this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
          }
        }
      });

      return;
    }
    const updatedUser: NewUser = { active: true } as NewUser;
    const formUser: User = this.formGroup.value;
    if(formUser.name && formUser.name !== this.selectedUser?.name) {
      updatedUser.name = formUser.name;
    }

    if(formUser.birthdate && formUser.birthdate !== this.selectedUser?.birthdate) {
      updatedUser.birthdate = formUser.birthdate;
    }

    if(formUser.email && formUser.email !== this.selectedUser?.email) {
      updatedUser.email = formUser.email;
    }

    if(formUser.role.id && formUser.role.id !== this.selectedUser?.role.id) {
      updatedUser.role = formUser.role;
    }

    if(formUser.password && formUser.password !== this.selectedUser?.password) {
      updatedUser.password = formUser.password;
    }

    try {
      if(!this.userId) {
        this.snackbar.open("Nem sikerült frissíteni, töltsd újra a módosítandú felhasználót!", 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
        return;
      }
      const res = await this.userService.updateUser(this.userId, updatedUser);
      this.snackbar.open(res, 'X', { duration: 3000, verticalPosition: 'bottom', panelClass: ['snackbar-success'] });
      await this.router.navigateByUrl("/admin/user", { skipLocationChange: true, replaceUrl: true });
      await this.router.navigateByUrl(`/admin/user/${this.userId}`, { replaceUrl: true });
    } catch(err) {
      this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
    }
  }

  captureValue = async (value: string) => {
    this.filter = value;
  }

  setValues = async (userId: number) => {
    try {
      this.userId = userId;
      this.selectedUser = await this.userService.getUser(userId);
      this.formGroup.setValue({
        name: this.selectedUser.name,
        birthdate: this.selectedUser.birthdate,
        email: this.selectedUser.email,
        role: this.selectedUser.role,
        password: ''
      });
      if(typeof this.selectedUser.active === "boolean") {
        this.activated = this.selectedUser.active;
      }
      if(this.activated) {
        this.formGroup.enable({ onlySelf: true });
      } else {
        this.formGroup.disable({ onlySelf: true });
      }
      this.router.navigateByUrl(`/admin/user/${userId}`, { replaceUrl: true });
    } catch(err) {
      this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
      this.router.navigateByUrl(`/admin/user`, { replaceUrl: true });
      this.resetValue();
    }
  }

  resetValue = () => {
    this.userId = undefined;
    this.selectedUser = undefined;
    this.formGroup.setValue({
      name: '',
    });
  }

  getRoleOptions = () => {
    return this.roles.map((role) => ({ value: role.id, shownValue: role.name, highlight: role.id === this.formGroup?.value.role.id }) as DropdownItem);
  }

  setRole = (roleId: number) => {
    if(!this.activated) {
      return;
    }

    const role = this.roles.find((rl) => rl.id === roleId);
    if(role) {
      this.formGroup.get("role")?.setValue(role);
    }
  }

  togglePasswordLock = () => {
    if(this.activated) {
      this.lockPassword = !this.lockPassword;
      if(this.lockPassword) {
        this.formGroup.get("password")?.disable({ onlySelf: true });
      } else {
        this.formGroup.get("password")?.enable({ onlySelf: true });
      }
    }
  }

  toggleActivate = () => {
    this.activated = !this.activated;
    if(this.activated) {
      this.formGroup.enable({ onlySelf: true });

    } else {
      this.formGroup.disable({ onlySelf: true });
    }
    this.lockPassword = true;
    this.formGroup.get("password")?.disable({ onlySelf: true });
  }
}

<div class="container">
  <div class="sub-container">
    <div class="search-field">
      <app-search-bar (searchValue)="captureValue($event)"></app-search-bar>
    </div>
    <div class="table">
      <app-user-table [searchValue]="filter" (selectedUserId)="setValues($event)"></app-user-table>
    </div>
  </div>
  <div class="sub-container" *ngIf="selectedUser">
    <div class="header">
      <h1>
        Felhasználó
      </h1>
      <div class="id">
        <label>ID: {{userId ? userId : '?'}}</label>
      </div>
    </div>
    <div class="form-container">
      <form [formGroup]="formGroup" (submit)="submit()">
        <div class="form-row">
          <mat-form-field class="form-col">
            <mat-label>Név</mat-label>
            <input matInput type="text" autocomplete="off" formControlName="name"/>
          </mat-form-field>
          <mat-form-field class="form-col">
            <mat-label>Születési dátum</mat-label>
            <input matInput type="date" autocomplete="off" formControlName="birthdate"/>
          </mat-form-field>
        </div>
        <div class="form-row">
          <mat-form-field class="form-col">
            <mat-label>Email</mat-label>
            <input matInput type="text" autocomplete="off" formControlName="email"/>
          </mat-form-field>
          <div class="form-col">
            <app-drop-down-bar
                [header]="'Szerepkör'" [options]="getRoleOptions()"
                [action]="true" [width]="'100%'" (selected)="setRole($event)"
                [changeHeader]="false"
            ></app-drop-down-bar>
          </div>
        </div>
        <div class="form-row">
          <mat-form-field class="form-col">
            <mat-label>Jelszó</mat-label>
            <input matInput type="text" autocomplete="off" formControlName="password"/>
            <button mat-icon-button matSuffix (click)="togglePasswordLock()" type="button">
              <mat-icon>{{lockPassword ? 'lock' : 'lock_open'}}</mat-icon>
            </button>
          </mat-form-field>
        </div>
        <div class="form-row">
          <div class="form-col form-footer">
            <div *ngIf="userId"></div>
            <button mat-raised-button type="submit">Mentés</button>
            <mat-slide-toggle [checked]="activated" (change)="toggleActivate()" *ngIf="userId">{{activated ? 'Aktiválva' : 'Deaktiválva'}}</mat-slide-toggle>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

// react-app/src/pages/handlers/user-handler/UserHandler.tsx
import { Button, FormControl, FormHelperText, Icon, IconButton, Input, InputAdornment, InputLabel, Switch, TextField } from '@mui/material';
import { AxiosError } from 'axios';
import { useCallback, useContext, useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { DropdownBar } from '../../../components/items/drop-down-bar/DropdownBar';
import { SearchBar } from '../../../components/items/search-bar/SearchBar';
import { UserTable } from '../../../components/user-table/UserTable';
import { SnackbarContext } from '../../../contexts/snackbarContext';
import { DropdownItem } from '../../../models/menu.model';
import { NewUser, Role, User } from '../../../models/user.model';
import { deleteUserRequest, getRolesRequest, getUserRequest, updateUserRequest } from '../../../utils/user-utils';
import * as yup from 'yup';
import styles from './UserHandler.module.css';
import { Confirmation } from '../../../components/items/confirmation/Confirmation';

type UserFormState = {
  id?: number;
  name: string;
  email: string;
  birthdate: string;
  role: Role;
  password?: string;
  active: boolean;
}

type UserFormErrorMessage = {
  [key in keyof UserFormState]?: string;
}

export const UserHandler = () => {
  const [roles, setRoles] = useState<Role[]>([]);
  const [userId, setUserId] = useState<number | undefined>(undefined);
  const [selectedUser, setSelectedUser] = useState<User | undefined>(undefined);
  const [searchValue, setSearchValue] = useState("");
  const [formState, setFormState] = useState<UserFormState>(formInit);
  const [errorMsg, setErrorMsg] = useState<UserFormErrorMessage>({});
  const [refreshToken, setRefreshToken] = useState(false);
  const [lockPassword, setLockPassword] = useState(true);
  const [openConfirmation, setOpenConfirmation] = useState(false);
  const { setMessage } = useContext(SnackbarContext);
  const navigate = useNavigate();
  const { id } = useParams();

  const submit = async (e: any) => {
    e.preventDefault();

    try {
      const response = await UserSchema.validate(formState, { abortEarly: false });

      if(response.active) {
        if(response.id) {
          const updatableUser: NewUser = { } as NewUser;
          if(response.name !== selectedUser.name) {
            updatableUser.name = response.name;
          }
          if(response.birthdate.split("T")[0] !== selectedUser.birthdate.split("T")[0]) {
            updatableUser.birthdate = response.birthdate.split("T")[0];
          }
          if(response.email !== selectedUser.email) {
            updatableUser.email = response.email;
          }
          if(response.role.id !== selectedUser.role.id) {
            updatableUser.role = response.role;
          }
          if(response.password !== selectedUser.password && !lockPassword) {
            updatableUser.password = response.password;
          }
          if(response.active) {
            updatableUser.active = response.active;
          }

          const resp = await updateUserRequest(response.id, updatableUser);
          if(resp) {
            setMessage(resp, "success");
            setRefreshToken(pre => !pre);
            fetchUserData(response.id);
          }
        } else {
          setMessage("Valami hiba történt!");
          reset();
        }
      } else {
        if(response.active !== selectedUser.active) {
          setOpenConfirmation(true);
 
        } else {
          reset();
        }
      }
    } catch(err) {
      if(err instanceof yup.ValidationError) {
        for(const error of err.inner) {
          errorMsg[(error.path as keyof UserFormState)] = error.message;
        }
        setErrorMsg(errorMsg);
      } else {
        if((err as AxiosError).response.status === 401) {
          navigate("/logout");
        }
        setMessage((err as AxiosError<any>).response.data.message);
      }
    }

  }

  const setSearchValueWrapper = (searchValue: string) => {
    setSearchValue(searchValue);
  }
  const setSelectedUserId = (id: number) => {
    navigate(`/admin/user/${id}`, { replace: true });
  }

  const toggleLockPassword = () => {
    setLockPassword(pre => !pre)
  }
  const handleFormFieldChange = (e: any, fieldName: string) => {
    setFormState((pre) => ({
      ...pre,
      [fieldName]: e.target.value,
    }));
  }
  const handleActivation = () => {
    setFormState((pre) => ({
      ...pre,
      active: !pre.active,
    }));
    setLockPassword(true);
  }
  const closeConfirmation = () => {
    setOpenConfirmation(false);
  }
  const deactivateUser = async () => {
    const resp = await deleteUserRequest(userId);
    if(resp) {
      setMessage(resp, "success");
      reset();
    }
  }

  const setSelectedRole = (roleId: number) => {
    const role = roles.find((rl) => rl.id === roleId);
    if(role) {
      setFormState((pre) => ({
        ...pre,
        role: role
      }));
    }
  }
  const getRoleOptions = useCallback(() => {
    return roles.map((role) => ({ value: role.id, shownValue: role.name, highlight: role.id === formState.role.id }) as DropdownItem);
  }, [formState.role, roles])
  const fetchUserData = useCallback(async (userId: number) => {
    try {
      const response = await getUserRequest(userId);
      if(response) {
        setSelectedUser(response);
        setLockPassword(true);
        setFormState({
          id: response.id,
          name: response.name,
          email: response.email,
          birthdate: response.birthdate,
          role: response.role,
          password: "",
          active: response.active,
        })
      }
    } catch(err) {
      if((err as AxiosError<any>).response.status === 401) {
        navigate("/logout");
      }
      setMessage((err as AxiosError<any>).response.data.message)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userId]);
  const fetchRoleData = useCallback(async () => {
    try {
      const response = await getRolesRequest();
      if(response) {
        setRoles(response);
      }
    } catch(err) {
      if((err as AxiosError<any>).response.status === 401) {
        navigate("/logout");
      }
      setMessage((err as AxiosError<any>).response.data.message)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const reset = () => {
    navigate("/admin/user");
    setUserId(undefined);
    setSelectedUser(undefined);
    setFormState(formInit);
    setErrorMsg({});
    setLockPassword(true);
    setRefreshToken((pre) => !pre);
  }

  useEffect(() => {
    fetchRoleData();
    if(!isNaN(Number(id))) {
      setUserId(Number(id));
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id]);
  useEffect(() => {
    if(userId) {
      fetchUserData(userId);
    }
  }, [fetchUserData, userId]);

  return (
    <div className={styles["container"]}>
      <Confirmation handleClose={closeConfirmation} open={openConfirmation} 
        question="Biztos deaktiválod a felhasználót?" onAccept={deactivateUser}
      />
      <div className={styles["sub-container"]}>
        <div className={styles["search-field"]}>
          <SearchBar setSearchValue={setSearchValueWrapper} />
        </div>
        <div className={styles["table"]}>
          <UserTable searchValue={searchValue} setSelectedUserId={setSelectedUserId} refreshToken={refreshToken} />
        </div>
      </div>
      {selectedUser &&
      <div className={styles["sub-container"]}>
        <div className={styles["header"]}>
          <h1>
            Felhasználó
          </h1>
          <div className={styles["id"]}>
            <label>ID: {selectedUser ? selectedUser.id : '?'}</label>
          </div>
        </div>
        <div className={styles["form-container"]}>
          <form onSubmit={submit}>
            <div className={styles['form-row']}>
              <div className={styles['form-col']}>
                <TextField label='Név' type='text' variant='standard' autoComplete='off' className={styles['form-col-input']}
                    value={formState.name} onChange={(e) => handleFormFieldChange(e, 'name')} InputLabelProps={{ style:{transformOrigin: "50%" }}}
                    error={errorMsg.name !== undefined} helperText={errorMsg.name} disabled={!formState.active}
                />
              </div>
              <div className={styles['form-col']}>
                <TextField label='Születési dátum' type='date' variant='standard' autoComplete='off' className={styles['form-col-input']}
                    value={formState.birthdate} onChange={(e) => handleFormFieldChange(e, 'birthdate')} InputLabelProps={{ style:{transformOrigin: "50%" }}}
                    error={errorMsg.birthdate !== undefined} helperText={errorMsg.birthdate} disabled={!formState.active}
                />
              </div>
            </div>
            <div className={styles['form-row']}>
              <div className={styles['form-col']}>
                <TextField label='Email' type='text' variant='standard' autoComplete='off' className={styles['form-col-input']}
                    value={formState.email} onChange={(e) => handleFormFieldChange(e, 'email')} InputLabelProps={{ style:{transformOrigin: "50%" }}}
                    error={errorMsg.email !== undefined} helperText={errorMsg.email} disabled={!formState.active}
                />
              </div>
              <div className={styles["form-col"]}>
                <DropdownBar
                    header='Szerepkör' options={getRoleOptions()} action={formState.active}
                    width='100%' changeHeader={false} setSelected={setSelectedRole}
                />
              </div>
            </div>
            <div className={styles['form-row']}>
            <div className={styles['form-col']}>
                <FormControl variant='standard' disabled={!formState.active || lockPassword} error={errorMsg.password !== undefined} className={styles['form-col-input']}> 
                  <InputLabel htmlFor='password-field' style={{transformOrigin: "50%"}}>Jelszó</InputLabel>
                  <Input id='password-field' type='text' autoComplete='off'
                      value={formState.password} onChange={(e) => handleFormFieldChange(e, 'password')}
                      endAdornment={
                        <InputAdornment position="end"  className={styles['lock-icon']}>
                          <IconButton
                            aria-label="Lock password"
                            onClick={toggleLockPassword}
                          >
                            <Icon>
                              { lockPassword ? 'lock' : 'lock_open'}
                            </Icon>
                          </IconButton>
                        </InputAdornment>
                      }
                  />
                  <FormHelperText>{errorMsg.password}</FormHelperText>
                </FormControl>
              </div>
            </div>
            <div className={styles["form-row"]}>
              <div className={styles["form-col form-footer"]}>
                {userId && <div></div>}
                <Button variant="contained" type="submit">Mentés</Button>
                {userId &&
                <>
                  <Switch checked={formState.active} onClick={handleActivation}/>
                  <span>{formState.active ? 'Aktiválva' : 'Deaktiválva'}</span>
                </>
                }
              </div>
            </div>
          </form>
        </div>
      </div>}
    </div>
  )
}

const UserSchema = yup.object().shape({
  id: yup.number().min(1),
  name: yup.string().required("A név megadása kötelező!"),
  email: yup.string().required("Az email megadása kötelező!").email("Valid email-nek kell lennie!"),
  birthdate: yup.string().required("A születési dátum megadása kötelező!"),
  role: yup.object({
    id: yup.number().min(1),
    name: yup.string()
  }),
  password: yup.string(),
  active: yup.boolean()
});

const formInit: UserFormState = {
  id: undefined,
  name: "",
  email: "",
  birthdate: "",
  password: "",
  role: {id: 0, name: 'unknown'},
  active: true,
}
