// react-app/src/components/items/series-item/SeriesItem.tsx
import { Icon, IconButton } from '@mui/material';
import { AxiosError } from 'axios';
import { FC, useContext, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AuthContext } from '../../../contexts/authContext';
import { SnackbarContext } from '../../../contexts/snackbarContext';
import { DropdownItem } from '../../../models/menu.model';
import { Series } from '../../../models/series.model';
import { User } from '../../../models/user.model';
import { hasRight } from '../../../utils/auth-utils';
import { getDefaultImageUrl, getImageUrlRequest } from '../../../utils/image-utils';
import { getCategories, getLimitColor, getSeasonOptions } from '../../../utils/series-utils';
import { defaultSaveUserSeriesRequest } from '../../../utils/userseries-utils';
import { DropdownBar } from '../drop-down-bar/DropdownBar';
import styles from './SeriesItem.module.css';

type SeriesItemProps = {
  series: Series,
  user?: User,
}

type SeriesItemState = {
  canAdd: boolean;
  canEdit: boolean;
}

export const SeriesItem: FC<SeriesItemProps> = ({ series, user }) => {
  const [options] = useState<DropdownItem[]>(getSeasonOptions(series));
  const [categories] = useState<string>(getCategories(series));
  const [state, setState] = useState<SeriesItemState>({ canAdd: false, canEdit: false });
  const [image, setImage] = useState<{ url: string, isDefault: boolean}>({ url: "", isDefault: true });
  const { setMessage } = useContext(SnackbarContext);
  const { logout } = useContext(AuthContext);
  const navigate = useNavigate();

  useEffect(() => {
    if(series.image?.name) {
      getImageUrlRequest(series.image?.name)
        .then((url) => {
          setImage({ url: url, isDefault: false});          
        })
        .catch((url) => {
          setImage({ url: url, isDefault: true});
        });
    } else {
      setImage({ url: getDefaultImageUrl(), isDefault: true});
    }
  }, [series]);

  useEffect(() => {
    const tempState: SeriesItemState = {} as SeriesItemState;
    tempState.canAdd = hasRight(["user"], user);
    tempState.canEdit = hasRight(["siteManager", "admin"], user);
    setState(tempState);
  }, [user]);

  const addSeries = async () => {
    try {
      if(series?.id) {
        await defaultSaveUserSeriesRequest(series?.id);
        setMessage("Sorozat sikeresen mentve!", "success");
      }
    } catch(err) {
      if((err as AxiosError).response?.status === 401) {
        logout();
      }
      setMessage((err as AxiosError<any>).response?.data.message);
    }
  }

  const editSeries = () => {
    navigate(`/admin/series/${series.id}`);
  }

  return (
    <div className={`${styles["series-item"]} ${image.isDefault ? styles["defaultImage"] : ""}`}
        style={{
          backgroundImage: `url(${image.url})`,
          backgroundPosition: `top ${series.image?.y_offset} left ${series.image?.x_offset}`
        }}
    >
      <div className={styles["float-button"]}>
        {state.canEdit && 
        <IconButton onClick={editSeries}>
          <Icon fontSize='small' className={styles["float-icon"]}>build</Icon>
        </IconButton>}
        { state.canAdd &&
        <IconButton className={styles["float-button"]} onClick={addSeries}>
          <Icon fontSize='small' className={styles["float-icon"]}>add</Icon>
        </IconButton>}
      </div>
      <header>
        <label className={styles["series-name"]}>{series.title}</label>
      </header>
      <div className={styles["series-item-body"]}>
        <div className={styles["series-prodyear"]}>{series.prodYear}</div>
        <div className={styles["series-length"]}>{series.length} perc</div>
        <div className={styles["series-category"]}>{categories}</div>
      </div>
      <footer>
        <label className={styles["age-limit"]} style={{ borderColor: getLimitColor(series.ageLimit)}}>{series.ageLimit}</label>
        <DropdownBar className={styles["season-drop-down"]} header="Évadok" width="100%" options={options}/>
      </footer>
    </div>
  );
}

// angular/src/app/components/items/series-item/series-item.component.ts
import { Component, Input, OnInit, OnChanges, SimpleChanges } from '@angular/core';
import { MatSnackBar } from '@angular/material/snack-bar';
import { Router } from '@angular/router';
import { DropdownItem, ErrorMessage } from 'src/app/models/menu.model';
import { Series } from 'src/app/models/series.model';
import { AuthService } from 'src/app/services/auth.service';
import { ImageService } from 'src/app/services/image.service';
import { UserSeriesService } from 'src/app/services/user-series.service';

@Component({
  selector: 'app-series-item',
  templateUrl: './series-item.component.html',
  styleUrls: ['./series-item.component.css']
})
export class SeriesItemComponent implements OnInit, OnChanges {
  @Input() series!: Series;
  canEdit: boolean;
  canAdd: boolean;
  imageUrl: string;
  options: DropdownItem[];
  offset: { x: string, y: string };
  constructor(private router: Router,
              private snackbar: MatSnackBar,
              private authService: AuthService,
              private userSeriesService: UserSeriesService,
              public imageService: ImageService,) {
    this.canEdit = false;
    this.canAdd = false;
    this.imageUrl = "";
    this.offset = { x: '25px', y: '-10px'};
    this.options = [];
  }

  async ngOnInit() {
    this.canEdit = this.authService.hasRight(["siteManager", "admin"]);
    this.canAdd = this.authService.hasRight(["user"]);
    if(this.series.image) {
      this.imageUrl = await this.imageService.getImageUrl(this.series.image?.name);
      this.offset = {
        x: this.series.image.x_offset as string,
        y: this.series.image.y_offset as string
      };
    } else {
      this.imageUrl = this.imageService.getDefaultImageUrl();
    }
  }

  ngOnChanges(changes: SimpleChanges): void {
    if(changes["series"]) {
      this.getOptions();
    }
  }

  getOptions = () => {
    if(!this.series || !this.series.seasons) {
      this.options = [];
    }

    for(const season of this.series.seasons.sort((a, b) => a.season - b.season)) {
      this.options.push({
        shownValue: `${season.season}.évad, ${season.episode} rész`,
        value: season.id
      });
    }
  }

  getCategories = (): string => {
    return this.series.categories.map((category) => category.name).join(', ');
  }

  getLimitColor = (): string => {
    if(!this.series || this.series.ageLimit >= 18) {
      return 'var(--red)';
    }

    if(this.series.ageLimit >= 16) {
      return '#F19F24'
    }

    if(this.series.ageLimit >= 12) {
      return '#FCFF5A'
    }

    return '#51D911'
  }

  editSeries = () => {
    this.router.navigateByUrl(`/admin/series/${this.series.id}`);
  }

  addSeries = async () => {
    try {
      if(this.series.id) {
        const response = await this.userSeriesService.defaultSaveUserSeries(this.series.id);
        if(response) {
          this.snackbar.open("Sorozat sikeresen felvéve!", 'X', { duration: 3000, verticalPosition: 'bottom', panelClass: ['snackbar-success'] });
        }
      }
    } catch(err) {
      this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
    }
  }
}

<div class="series-item" [ngStyle]="{'background-image': 'url('+imageUrl+')',
      'background-position': 'top '+ offset.y +' left ' + offset.x }"
      [ngClass]="{'defaultImage': imageService.getDefaultImageUrl() === imageUrl}"
>
  <button class="float-button" mat-icon-button (click)="editSeries()" *ngIf="canEdit">
    <mat-icon class="float-icon">build</mat-icon>
  </button>
  <button class="float-button" mat-icon-button (click)="addSeries()" *ngIf="canAdd">
    <mat-icon class="float-icon">add</mat-icon>
  </button>
  <header>
    <label class="series-name">{{series.title}}</label>
  </header>
  <div>
    <div class="series-prodyear">{{series.prodYear}}</div>
    <div class="series-length">{{series.length}} perc</div>
    <div class="series-category">{{getCategories()}}</div>
  </div>
  <footer>
    <label class="age-limit" [ngStyle]="{'border-color': getLimitColor()}">{{series.ageLimit}}</label>
    <app-drop-down-bar class="season-drop-down" [header]="'Évadok'" [width]="'100%'" [options]="options"></app-drop-down-bar>
  </footer>
</div>
