// angular/src/app/components/navbar/navbar.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs';
import { Event, NavigationEnd, Router } from '@angular/router';
import { User } from 'src/app/models/user.model';
import { AuthService } from 'src/app/services/auth.service';
import { SidebarItem } from 'src/app/models/menu.model';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit, OnDestroy {
  private routerSub!: Subscription;
  private userSub!: Subscription;
  user?: User;
  sidebarItems?: SidebarItem[];
  isLoginPage: boolean;

  constructor(private authService: AuthService, private router: Router) {
    this.isLoginPage = false;
  }

  ngOnInit(): void {
    this.routerSub = this.router.events.subscribe((event: Event) => {
      if(event instanceof NavigationEnd) {
        const { url } = event;
        if(url === "/login"){
          this.isLoginPage = true;
        } else {
          this.isLoginPage = false;
        }
      }
    });

    this.user = this.authService.getUser();
    if(this.user) {
      this.sidebarItems = this.authService.getSidebarItems();
    }
    this.userSub = this.authService.getUserObserver((nextUser) => {
      this.user = nextUser;
      this.sidebarItems = this.authService.getSidebarItems();
    })
  }

  ngOnDestroy(): void {
    if(!this.routerSub.closed) {
      this.routerSub.unsubscribe();
    }
    if(!this.userSub.closed) {
      this.userSub.unsubscribe();
    }
  }

  hasUser = (): boolean => {
    return this.user !== undefined;
  }
}

<header id="navbar">
  <section id="left-navbar-section" class="navbar-section">
    <app-sidebar *ngIf="sidebarItems !== undefined" [items]="sidebarItems"></app-sidebar>
    <a routerLink="/series" title="Sorozatok" mat-button class="navbar-button">Sorozatok</a>
    <a routerLink="/newsfeed" title="Újdonságok" mat-button class="navbar-button">Újdonságok</a>
  </section>
  <section id="middle-navbar-section" class="navbar-section">
    <app-profile *ngIf="hasUser(); else noUser" [user]="user"></app-profile>
    <ng-template #noUser>
        <a routerLink="/login" title="Bejelentkezés" mat-button *ngIf="!isLoginPage; else inSignUp">
          <mat-icon class="navbar-auth-icon">key</mat-icon>
          <span class="navbar-auth-text">Bejelentkezés</span>
        </a>
        <ng-template #inSignUp>
          <a routerLink="/signup" title="Regisztráció" mat-button>
            <mat-icon class="navbar-auth-icon">settings_accessibility</mat-icon>
            <span class="navbar-auth-text">Regisztráció</span>
          </a>
        </ng-template>
    </ng-template>
  </section>
  <section id="right-navbar-section" class="navbar-section">
    <app-backend-chooser></app-backend-chooser>
  </section>
</header>

// react-app/src/components/navbar/Navbar.tsx
import { useContext } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { AuthContext } from '../../contexts/authContext';
import { Profile } from '../profile/Profile';
import { Sidebar } from '../sidebar/Sidebar';
import styles from './Navbar.module.css';
import { Icon } from '@mui/material';
import { BackendChooser } from '../backend-chooser/BackendChooser';

export function Navbar() {
  const { user } = useContext(AuthContext);
  const currentPath = useLocation().pathname;

  return (
    <header id={styles["navbar"]}>
      <section id={styles["left-navbar-section"]} className={styles["navbar-section"]}>
        <Sidebar></Sidebar>
        <Link to={"/series"} title="Sorozatok" className={styles["navbar-button"]}>Sorozatok</Link>
        <Link to={"/newsfeed"} title="Újdonságok" className={styles["navbar-button"]}>Újdonságok</Link>
      </section>
      <section id={styles["middle-navbar-section"]} className={styles["navbar-section"]}>
        {user 
        ? <Profile></Profile>
        : currentPath === "/login"
        ? <Link to={"/signup"} className={styles["navbar-main-button"]} title="Regisztráció">
            <Icon className={styles["navbar-auth-icon"]}>settings_accessibility</Icon>
            <span className={styles["navbar-auth-text"]}>Regisztráció</span>
          </Link>
        : <Link to={"/login"} className={styles["navbar-main-button"]} title="Bejelentkezés">
            <Icon className={styles["navbar-auth-icon"]}>key</Icon>
            <span className={styles["navbar-auth-text"]}>Bejelentkezés</span>
          </Link>
        }
      </section>
      <section id={styles["right-navbar-section"]} className={styles["navbar-section"]}>
        <BackendChooser></BackendChooser>
      </section>
    </header>
  );
}
