// react-app/src/components/items/drop-down-bar/DropdownBar.tsx
import { Icon } from '@mui/material';
import { FC, useRef, useState } from 'react';
import { DropdownItem } from '../../../models/menu.model';
import { useClickOutside } from '../../../utils/component-utils';
import styles from './DropdownBar.module.css';

type DropdownBarProps = {
  options: DropdownItem[],
  width?: string,
  header?: string,
  action?: boolean,
  setSelected?: (selected: any) => void,
  changeHeader?: boolean,
  className?: string,
}

export const DropdownBar: FC<DropdownBarProps> = ({ options, width = '280px', header = 'Unknown', action = false, changeHeader = true, setSelected, className }) => {
  const [open, setOpen] = useState(false);
  const [selectedValueHeader, setSelectedValueHeader] = useState(header);
  const componentRef = useRef<any>(null);

  const toggle = () => {
    setOpen((pre) => !pre);
  }
  const close = () => {
    setOpen(false);
  }

  const selectHandle = (option: DropdownItem) => {
    if(!action) {
      return;
    }
    if(changeHeader) {
      if(!option.value) {
        setSelectedValueHeader(header);
      } else {
        setSelectedValueHeader(option.shownValue);
      }
    }

    if(setSelected !== undefined) {
      setSelected(option.value);
    }
  }

  useClickOutside(componentRef, close);
  return (
    <div
      className={`${styles["dropdown-container"]} ${className ? className : ""}`}
      style={{
        width: width,
        borderRadius: open ? '8px 8px 0px 0px' : '8px',
      }}
      ref={componentRef}
      >
      <div className={styles["dropdown-header"]} onClick={toggle}>
        <label>{selectedValueHeader}</label>
        <label>
          <Icon className={`${styles["dropdown-icon"]} ${open ? styles["expanded"] : ''}`}>expand_more</Icon>
        </label>
      </div>
      <div className={`${styles["dropdown-body"]} ${open ? styles['open'] : ''}`}>
        {
          options.length > 0
          ? <span>
            <span className={styles["dropdown-item-container"]}>
            {
              options.map((option, index) => (
                <div className={`${styles["dropdown-body-item"]} ${option.highlight ? styles['highlight'] : ''}`}
                onClick={() => selectHandle(option)} key={index}
                  >{option.shownValue}</div>
              ))
            }
            </span>
          </span>
          : <span className={styles["dropdown-item-container"]}>
            <div className={styles["dropdown-body-item"]}>
              Üres...
            </div>
          </span>
        }
      </div>
    </div>
  )
}

// angular/src/app/components/items/drop-down-bar/drop-down-bar.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { DropdownItem } from 'src/app/models/menu.model';

@Component({
  selector: 'app-drop-down-bar',
  templateUrl: './drop-down-bar.component.html',
  styleUrls: ['./drop-down-bar.component.css']
})
export class DropDownBarComponent implements OnInit {
  open: boolean;
  @Input() header: string;
  @Input() width: string;
  @Input() changeHeader: boolean;
  @Input() options: DropdownItem[];
  @Input() action: boolean;
  @Output() selected = new EventEmitter<any>();
  selectedValue!: string | number;

  constructor() {
    this.open = false;
    this.action = false;
    this.width = '280px';
    this.changeHeader = true;
    this.options = [];
    this.header = "Unknown";
  }

  ngOnInit(): void {
    this.selectedValue = this.header;
  }

  toggle = ():void => {
    this.open = !this.open;
  }

  close = (): void => {
    this.open = false;
  }

  onClick = (selectedValue: DropdownItem) => {
    if(!this.action) {
      return;
    }
    if(this.changeHeader) {
      if(!selectedValue.value) {
        this.selectedValue = this.header;
      } else {
        this.selectedValue = selectedValue.shownValue;
      }
    }
    this.selected.emit(selectedValue.value);
  }

  getIcon = (): string => {
    return this.open ? "expand_less" : "expand_more";
  }
}

<div class="dropdown-container" [style.width]="width"
  (clickOutside)="close()"
  [ngStyle]="{'border-radius': open ? '8px 8px 0px 0px' : '8px'}">
  <div class="dropdown-header" (click)="toggle()">
    <label>{{selectedValue}}</label>
    <label>
      <mat-icon class="dropdown-icon">{{open ? "expand_less" : "expand_more"}}</mat-icon>
    </label>
  </div>
  <div class="dropdown-body" *ngIf="open"
  [ngStyle]="{'border-top': open ? '2px solid var(--primary-color)' : 'none'}">
    <span *ngIf="this.options && this.options.length > 0; else noOptions">
      <span class="dropdown-item-container" *ngFor="let option of options">
        <div class="dropdown-body-item" [ngClass]="{ 'highlight': option.highlight }"
          (click)="onClick(option)">{{option.shownValue}}</div>
        <!-- <hr class="divider" /> -->
      </span>
    </span>
    <ng-template #noOptions>
      <span class="dropdown-item-container">
        <div class="dropdown-body-item">
          Üres...
        </div>
      </span>
    </ng-template>
  </div>
</div>
