// angular/src/app/pages/newsfeed/newsfeed.component.ts
import { Component, HostListener, OnInit } from '@angular/core';
import { MatSnackBar } from '@angular/material/snack-bar';
import { Router } from '@angular/router';
import { DropdownItem, ErrorMessage, PageOptions, PageOptionsKeys } from 'src/app/models/menu.model';
import { Newsfeed } from 'src/app/models/newsfeed.model';
import { NewsfeedService } from 'src/app/services/newsfeed.service';

@Component({
  selector: 'app-newsfeed',
  templateUrl: './newsfeed.component.html',
  styleUrls: ['./newsfeed.component.css']
})
export class NewsfeedComponent implements OnInit {
  newsfeeds: Newsfeed[];
  count: number;
  opts: PageOptions;
  orderOptions: DropdownItem[];
  private isPersonal!: boolean;
  constructor(private newsfeedService: NewsfeedService,
              private snackbar: MatSnackBar,
              private route: Router) {
    this.newsfeeds = [];
    this.count = -1;
    this.opts = {
      page: 1,
      size: 10,
      direction: true
    };
    this.orderOptions = [];
  }

  ngOnInit(): void {
    if(this.route.url === "/user/newsfeed") {
      this.isPersonal = true;
    } else {
      this.isPersonal = false;
    }
    this.getNewsfeeds();
    this.orderOptions = this.newsfeedService.getOrders();
  }

  getNewsfeeds = async () => {
    this.opts["page"] = 1;
    try {
      const response = this.isPersonal
      ? await this.newsfeedService.getPersonalNewsfeeds(this.opts.page, this.opts.size, this.opts.filter, this.opts.order, this.opts.direction)
      : await this.newsfeedService.getNewsfeeds(this.opts.page, this.opts.size, this.opts.filter, this.opts.order, this.opts.direction);
      this.newsfeeds = response.newsfeeds ?? [];
      this.count = response.count;
    } catch(err) {
      this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
    }
  }

  pushNewsfeeds = async () => {
    if(this.newsfeeds.length === this.count) {
      return;
    }

    try {
      const response = this.isPersonal
      ? await this.newsfeedService.getPersonalNewsfeeds(this.opts.page, this.opts.size, this.opts.filter, this.opts.order, this.opts.direction)
      : await this.newsfeedService.getNewsfeeds(this.opts.page, this.opts.size, this.opts.filter, this.opts.order, this.opts.direction);
      this.newsfeeds.push(...response.newsfeeds);
      this.count = response.count;

    } catch(err) {
      this.snackbar.open((err as ErrorMessage).error.message, 'X', { duration: 6000, verticalPosition: 'bottom', panelClass: ['snackbar-error'] });
    }
  }

  setOption = (name: PageOptionsKeys, value: string | number | boolean) => {
    this.opts[name] = value as never;
    this.getNewsfeeds();
  }

  @HostListener("window:scroll", ["$event"])
  onWindowScroll() {
    if(this.newsfeeds.length !== this.count) {
      let pos = (document.documentElement.scrollTop || document.body.scrollTop) + document.documentElement.offsetHeight;
      let max = document.documentElement.scrollHeight - 100;

      if(pos >= max)   {
        this.opts["page"] += 1;
        this.pushNewsfeeds();
      }
    }
  }
}

<main class="container">
  <header class="search">
    <div class="search-item">
    </div>
    <div class="search-item">
      <app-search-bar (searchValue)="setOption('filter', $event)"></app-search-bar>
      <mat-slide-toggle class="direction" [checked]="opts.direction" (change)="setOption('direction', !opts.direction)">{{opts.direction ? "Növekvő sorrend" : "Csökkenő sorrend"}}</mat-slide-toggle>
    </div>
    <div class="search-item">
      <app-drop-down-bar [action]="true" [header]="'Rendezés'" [options]="orderOptions" (selected)="setOption('order', $event)"></app-drop-down-bar>
    </div>
  </header>
  <div class="items" *ngIf="newsfeeds.length > 0; else noNewsfeed">
    <div >
      <app-newsfeed-item [newsfeed]="newsfeed" *ngFor="let newsfeed of newsfeeds"></app-newsfeed-item>
    </div>
  </div>
  <ng-template #noNewsfeed>
    <div class="items" style="text-align: center">
      <h1>Nincsennek megjeleníthető újdonság</h1>
    </div>
  </ng-template>
</main>

// react-app/src/pages/newsfeed/Newsfeed.tsx
import { Switch } from '@mui/material';
import { AxiosError } from 'axios';
import { useCallback, useContext, useEffect, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { DropdownBar } from '../../components/items/drop-down-bar/DropdownBar';
import { NewsfeedItem } from '../../components/items/newsfeed-item/NewsfeedItem';
import { SearchBar } from '../../components/items/search-bar/SearchBar';
import { AuthContext } from '../../contexts/authContext';
import { DetectBottomContext } from '../../contexts/detectBottomContext';
import { SnackbarContext } from '../../contexts/snackbarContext';
import { DropdownItem } from '../../models/menu.model';
import { NewsfeedPageModel } from '../../models/newsfeed.model';
import { hasRight } from '../../utils/auth-utils';
import { getNewsfeedsRequest, getOrders, getPersonalNewsfeedsRequest } from '../../utils/newsfeed-utils';
import styles from './Newsfeed.module.css';

type NewsfeedState = {
  page: number;
  size: number;
  filter?: string;
  order?: string;
  direction?: boolean;
}

export const Newsfeed = () => {
  const [orders] = useState<DropdownItem[]>(getOrders());
  const [state, setState] = useState<NewsfeedState>({ page: 1, size: 12, direction: false });
  const [newsfeed, setNewsfeed] = useState<NewsfeedPageModel>({ newsfeeds: [], count: -1 });
  const { setMessage } = useContext(SnackbarContext);
  const { logout, user } = useContext(AuthContext);
  const { reachedBottom } = useContext(DetectBottomContext);
  const currentPath = useLocation().pathname;
  
  const increasePageSize = useCallback(() => {
    if(newsfeed.newsfeeds.length < newsfeed.count && state.page*state.size < newsfeed.count) {
      setState((pre) => ({
        ...pre,
        page: pre.page + 1,
      }));
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[newsfeed]);

  const fetchData = useCallback(async () => {
    if(state.page > 1) {
      await pushNewsfeeds();
    } else {
      if(currentPath === "/user/newsfeed") {
        if(hasRight(["user"], user)) {
          await getPersonalNewsfeeds();
        } else {
          setMessage("Nem sikerült az újdonságok betöltése, próbáld újra!");
        }
      } else {
        await getNewsfeeds();
      }
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [state]);
  const getNewsfeeds = async () => {
    try {
      const response = await getNewsfeedsRequest(1, state.size, state.filter, state.order, state.direction);
      setNewsfeed({ count: response.count, newsfeeds: response.newsfeeds });
    } catch(err) {
      if((err as AxiosError).response?.status === 401) {
        logout();
      }
      setMessage((err as AxiosError<any>).response?.data?.message);
    }
  }

  const getPersonalNewsfeeds = async () => {
    try {
      const response = await getPersonalNewsfeedsRequest(1, state.size, state.filter, state.order, state.direction);
      setNewsfeed({ count: response.count, newsfeeds: response.newsfeeds });
    } catch(err) {
      if((err as AxiosError).response?.status === 401) {
        logout();
      }
      setMessage((err as AxiosError<any>).response?.data?.message);
    }
  }

  const pushNewsfeeds = async () => {
    try {
      const response = await getNewsfeedsRequest(state.page, state.size, state.filter, state.order, state.direction);
      setNewsfeed((pre) => ({
        count: response.count,
        newsfeeds: [...pre.newsfeeds, ...response.newsfeeds]
      }));
    } catch(err) {
      if((err as AxiosError).response?.status === 401) {
        logout();
      }
      setMessage((err as AxiosError<any>).response?.data?.message);
    }
  }

  const handleSelectedOrder = (value: string) => {
    setState((pre) => ({
      ...pre,
      order: value,
      page: 1,
    }))
  }

  const handleSearchValue = (searchValue: string) => {
    setState((pre) => ({
      ...pre,
      filter: searchValue,
      page: 1,
    }))
  }

  const handleDirection = () => {
    setState((pre) => ({
      ...pre,
      direction: !pre.direction,
      page: 1,
    }))
  }

  useEffect(() => {
    if(reachedBottom) {
      increasePageSize();
    }
  }, [reachedBottom, increasePageSize]);

  useEffect(() => {
    fetchData();
  }, [fetchData, state])

  return (
    <main className={styles["container"]}>
      <header className={styles["search"]}>
        <div className={styles["search-item"]}>
        </div>
        <div className={styles["search-item"]}>
          <SearchBar setSearchValue={handleSearchValue} />
          <div className={styles["direction"]}>
            <Switch size='medium' checked={state.direction} onClick={handleDirection}/>
            <span>{state.direction ? "Növekvő sorrend" : "Csökkenő sorrend"}</span>
          </div>
        </div>
        <div className={styles["search-item"]}>
          <DropdownBar action={true} header="Rendezés" options={orders} setSelected={handleSelectedOrder}/>
        </div>
      </header>
      {
        newsfeed.newsfeeds.length > 0
        ? <div className={styles["items"]}> 
            <div >
              {newsfeed.newsfeeds.map((newsfeed) => (
                <NewsfeedItem key={newsfeed.id} newsfeed={newsfeed} user={user} />
                ))}
            </div>
          </div>
        : <div className={styles["items"]} style={{ textAlign: "center"}}>
            <h1>Nincsennek megjeleníthető újdonság</h1>
          </div>
      }
    </main>
  )
}
